### ISSUE TITLE
How "fair" is the current Trust metric system: Analyzing its effectiveness

### ISSUE THREAD

**Issue by David405** [rchain/bounties#752] opened 2018-06-03 19:00 UTC
In 201805 pay period, the trust rating was put into place to be used for voting on budgets and rewards. Out of about 109 issues that have received votes for May pay period, about 80% of the rewards goes to 
persons with trust ratings. 

On issues where people with trust ratings and those without it collaborated, those with trust ratings usually have far higher percentages than the others (which is okay because voters will always seek to protect their rewards first before others).

On issues where none of the participants have trust ratings and they have to solicit for votes from people certified by the trust rating, there seems to be a lot of unfairness because the rewards votes are not fairly distributed among the participants as the voters did not partake in the task/project and so do not know who did the most work and who did a minimal job.

I understand that the Trust metric system is put in place to prevent fraud and encourage fairness but it's current state cannot accomplish this for some obvious reasons:

- Humans tend to protect their interest first before any other and this is natural, so most times, during voting on collaborative projects, members with trust rating will naturally vote for themselves before any other. _(This can be seen in democratic and cooperative societies)_

- On issues where none of the collaborators have the trust rating, it is difficult for an external voter to give a right judgement as to who gets what percentage of the reward simply because the external voter do not have an idea on the individual contributions.

- Members without trust rating have to solicit for reward votes from members whose votes carry weight, sometimes these voters with trust rating take days _(weeks in some cases while some never reply)_ before responding to their messages and then they end up voting based on their judgement and from an informed objective point of view.

**Possible Amendments**

- I believe every member of the coop should have a right to protect his/her interest in rewards and voting. There may be people whose votes carry more weight but at least a member should be given the right to vote for himself/herself on a project he/she participated in. 

- Guides should be able to give suggestions as to how much budget an issue is worth.

- Another possible amendment(_I don't support this due to the stress involved but it can also be considered_) Voters with trust rating should be tasked with voting for others without the trust rating.

**This should be added to the agenda of 20180606 member meeting**

_Estimated Budget of Participation:_ **$[400]**
_How will we measure completion?_ **[Amendment to Trust metric system]**

cc: @dckc @lapin7 @jimscarver @kitblake @ian-bloom @pmoorman @allancto and everyone

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

**Comment by dckc** [comment] 2018-06-03 20:08
The most straightforward change to the existing system is to tweak the parameters for the expected number of masters, journeyers, and apprentices; for example on May 9: https://github.com/rchain/bounties/issues/375#issuecomment-387924526

As motivation for this or other changes, please give two or three specific examples where the current system is working poorly.

(We have another 5 days to address them before the 201805 pay period voting closes, of course.)

> Guides should be able to give suggestions as to how much budget an issue is worth.

They are already able to do so, no? If not, please give an example.

p.s. Where exactly did those numbers come from? When you say "80% of rewards" do you mean by dollar amount? Or by counting issue / worker combinations? I get:


has_rating | count(*) |   | sum(reward_usd) |  
-- | -- | -- | -- | --
0 | 53 | 34.64% | 4258 | 27.06%
1 | 100 | 65.36% | 11480 | 72.94%
  | 153 |   | 15738 |  

```sql
select has_rating, count(*), sum(reward_usd)
from (
	select pay.issue_num, pay.worker, reward_usd
	     , case when a.rating is null then 0 else 1 end has_rating
	from reward pay
	left join authorities a on pay.worker = a.login
	where pay.pay_period = '2018-05-01'
) detail
group by has_rating;
```


I can't reproduce the 109. I can find:

   - 153 [rewards (issue + worker) in the 201805 pay period with votes](https://rewards.rchain.coop/index.php?-table=reward&-limit=30&issue_num=&title=&worker=&reward_usd=&percent_avg=&budget_usd=&voter_qty=&voters=&reward_provisional=&budget_provisional=&pay_period=05%2F01%2F2018&labels=)
      - 27 [with reward > 0](https://rewards.rchain.coop/index.php?-table=reward&-limit=30&reward_usd=%3E0&pay_period=05%2F01%2F2018)
  - 102 [issues with budget votes](https://rewards.rchain.coop/index.php?-table=issue_budget&-limit=30&issue_num=&title=&budget_usd=&budget_provisional=&voter_qty=&voters=&pay_period=05%2F01%2F2018&labels=)

p.p.s. what is the **discussion** label for? Doesn't every issue involve discussion?

And the title of the issue says it is only about analyzing the effectiveness of the trust metric, but the **bounty-contract** label suggests it's a change to the process, and you note some proposed changes, and the measure of completion is that the trust metric is amended. I guess we'll see where we end up...

And why the quotes around "fair"? You're using the word in its usual sense, no?

**Comment by David405** [comment] 2018-06-04 08:20
@dckc I think you need to update your records, Here are the total rewards so far: Members with trust ratings have a total rewards of **$14,911** while members without trust rating has a total of **4,858 see [here](https://docs.google.com/spreadsheets/d/1HpakW3IZgJO6XBpVtJ3WYJjGd7KSpgYhBeGBa_WhltE/edit#gid=0). This is what I mean by "about 80% of rewards".

@TrenchFloat, you voted 5% for Makys on #672 but I don't see her input, maybe you might want to explain this, also, @jimscarver voted 5% for @ICA3DaR5 ON #681 where there was no input from @ICA3DaR5 and 25% for @nonnykul who is the main actor on the project. How do we co-relate this?

_PS- All figures were given as at 20180604 9:00am GMT+1_

**Comment by Valentine-Mario** [comment] 2018-06-04 08:31
Nice observation @David405 I think the current method of voting is quite biased and elitist. To make the voting process easier, I suggest that each label lead should vote for issues in their label and people voted for should also raise concerns if they feel their vote is insufficient or bias. This would create a more transparent system that is open to scrutiny. 

Another method that could be possible is that each issue when voted for should submit a statement of the amount of work done and everyone's capacity who participated in the issue to the trust metric members .

**Comment by David405** [comment] 2018-06-04 08:36
From the ongoing work in #471 by @jimscarver @barneycinnamon, it was stated [here](https://docs.google.com/document/d/1Sv0iPxufWezcKsQKrIoI3EXMEgvvAzXQN2Pjsn3jIcI/edit#) that RChain as a coop subscribes to the International Co-op Alliance’s set of Principles

> RChain Co-op Principles being considered: (add your own and comment)
As a Co-op, RChain Co-op already subscribes to the International Co-op Alliance’s set of Principles:
Cooperative Principles 

 Open and Voluntary Membership. ...
 Democratic Member Control. …
 Members' Economic Participation. …
 Autonomy and Independence. …
 Education, Training, and Information. …
 Cooperation Among Cooperatives. ...
 Concern for Community.

**Comment by David405** [comment] 2018-06-04 09:11
@dckc I would like to address your subsequent questions here, 

Firstly, You asked about the **discussion** label, I add discussion labels to issues which do not involve any tasks or projects _( not all issues require tasks to be carried out and thus there have to be a way to separate issues based on this parameter)_.

Secondly, you asked about the **bounty-contract** label, the aim of the issue is to propose a change to the bounty-contract with regards to the aspect of **Trust ratings**, I believe **every** member of RChain coop should be able to vote and influence rewards and budgets on issues they participated in, label guides should also be able to put a check on budgets too.

Finally, you asked about the double quotes around the word _fair_, the double quotes were placed to show emphasis and nothing more.

**Comment by lapin7** [comment] 2018-06-04 09:46
What happens if we reverse the system? Every member starts as journeyer until s/he blows it. 
The assumption is that there more good actors then bad actors. 
All members can demote or promote the certification of all members.

**Comment by jasoncruzzy** [comment] 2018-06-04 12:09
Nice Observation @David405

**Comment by David405** [comment] 2018-06-04 13:28
@lapin7 I agree with your suggestion especially the part you said **ALL MEMBERS**

I believe on of the structures that should be changed in the bounty program is the structure of a few persons making all the decisions for everyone. The {Cooperative Principles](https://ica.coop/en/whats-co-op/co-operative-identity-values-principles) states

> 7. Concern for Community
Co-operatives work for the sustainable development of their communities through policies approved by their members.

I think before any idea or suggestion is implemented in a cooperative, there should be a consensus by the _majority_  of its members but for a while now in the RChain coop, ideas have been implemented without even proper information passed across to all members of the cooperative.

For example, in #653 the voters voted 0 as budget and rewards for @Pionelle and since the weight was more than 10x, she has lost her rewards in her other issues for the month, **When was there a consensus that voting 0 or a neagtive number on an issue cancels reward for the month?**, who and who were present in such meeting? How many members agreed to it? I think it is high time we reform some of the structures we have in place if we truly refer to ourselves as a cooperative.

**Comment by pmoorman** [comment] 2018-06-04 13:58
Hey @David405 you seem to imply that right now we have a _"structure of a few persons making all the decisions for everyone."_

I don't think that's currently the case: there are currently 46 people certified under the Trust Metric system to have a vote that counts, and more people can be added whenever the trust trusts them. That's hardly elitist or centralised! 

As a matter of fact, I think **the RChain Bounty System is an absolute front-runner when it comes to decentralised governance**, and something to be proud of (even if it's still experimental).

...

The idea of a _majority_ of the members (which means 1000+ people) agreeing on every idea and concept is unworkable in practice.

The concept of the Trust Metric has been in the works since February, and @dckc has always worked completely transparently, in the open. I think he's shown incredibly concern for the community with his work.

As for slashing, this has similarly been in the works since early this year, and also completely transparently. Slashing was already in place in December last year, when @Mervyn853 effectively slashed @ResonanceXX. This is not by any means a new idea.

...

Finally, I think @dckc would greatly appreciate any help on the bounty app he can get. If you know of any devs that are keen to help, send them our way so that they can help out!

**Comment by BelovedAquila** [comment] 2018-06-04 14:48
Personally I have been trying to relate RChain as a cooperative to the trust metric system too,don't understand how they both could work together without hampering the legitimacy and dictums of A COOPERATIVE.
The trust metric system ranking is obviously bias, I am still wondering on the basis at which the ranks was placed. Slashing was sufficiently enough to curtail and sanction bad actors and perform to the effect of the vital factors for which the trust metric system was put in place. but yet we have to bring ranks into the system, creating authoritarianism and power imposed loyalty. Cooperative has no close relationship with authoritarianism or dictatorship like I always had known but I am moved to find out if things has changed without my being current to them. The coop is strictly endeavoring to prevent any trace of dominance or ascendance on the basis of it being a cooperative platform, 
Just as dckc attested 
 >I'm pretty sure @lapin7 and many others are trying pretty hard to avoid "supervisor" roles, but the current situation is turning away potential developer contributions, as noted in #483:<
 in acceptance to lapins same proposition to prevent lateralization of power and function in the coop. Using issue #471 as a quick reference point to RChain's cooperative principles and values, I think the trust metric system and some other bias, domineering occurrences going on are gradually going against the laws of cooperative governing rchain as a coop. And as bad as that could be, it's obvious enough we might actually be contradicting ourselves by the use of the new trust metric system and maintaining of RChain being a cooperative #213. 

>Guides should be able to give suggestions as to how much budget an issue is worth.<

Yes, although so far what is being done by some projects guides is in line and productive to an extent, but the issue of not giving detailed specifications as to what is fair in respect to the budgets is not helping the budget system work smoothly. just like I am trying to still figure out what is considered a fair percentage to be allocated for a review of a doc, what is fair for an issue and how is fair to reward contributors of an issue.since we are not seeming to  accept the assumptions that those who worked on the issues knows what it's worth and who gets what.

**Comment by dckc** [comment] 2018-06-04 15:22
@lapin7 writes:
> What happens if we reverse the system? Every member starts as journeyer until s/he blows it.

I don't see how to square that with the Apr 6 TOS decision by the board (#616). It seems to me that we tried the "everybody gets to vote on budgets and rewards" approach and the board decided it got abused.

**Comment by dckc** [comment] 2018-06-04 15:43
> In #653 the voters voted 0 as budget and rewards for @Pionelle and since the weight was more than 10x, she has lost her rewards in her other issues for the month

Yes, well, she voted (Tue May 8 10:59:46 2018) to reward thousands of dollars for work that is not done. I stand by my claim that this is not fair. As I said May 17, all she has to do is delete that vote:

> If you want me to withdraw my slashing vote, ... change your votes ...

**Comment by David405** [comment] 2018-06-04 15:59
@dckc says: 

> Yes, well, she voted (Tue May 8 10:59:46 2018) to reward thousands of dollars for work that is not done. I stand by my claim that this is not fair. 

On Mar 31, #375, you suggested a $2000 for a work that was not yet done:

> I suggest a budget of $2000 for March. This isn't done, but I think significant value has already been delivered.

Does it mean that your action was a bad action and required slashing?

**Comment by dckc** [comment] 2018-06-04 16:16
I suggested a budget. I didn't claim a reward.

**Comment by dckc** [comment] 2018-06-04 16:17
Rather: I claimed a reward for the part that was done and available for all to see.

**Comment by Tonyprisca13** [comment] 2018-06-04 18:57
The trust metric is totally baised and is centralized. All active member should have a say on certification of any member not just a few members or a particular member.

**Comment by Tonyprisca13** [comment] 2018-06-04 20:01
@david writes on discord < Also, @dckc: I would like you to explain when there was a consensus that a member will lose his/her monthly rewards when he/she receives 0  usd votes of more than 10x weight>
@dckc reply< May 9 is when I made the decision, IIRC. To be sure, check #261>
This was implemented into the trust metric without a consensus form the RAM. My concern is why should such a KEY decision be made without consensus  in a decentralized cooperative.

**Comment by dckc** [comment] 2018-06-04 20:13
without a consensus? Who objected? What did I miss?

**Comment by BelovedAquila** [comment] 2018-06-04 20:23
>Yes, well, she voted (Tue May 8 10:59:46 2018) to reward thousands of dollars for work that is not done. I stand by my claim that this is not fair. As I said May 17, all she has to do is delete that vote:<

@dckc you ask that the budget be changed, on the basis of it not being fair even though you understood little to nothing as to the work done on it, and that I accepted and requested to know which budget was considered fair, but got no reply. Presently you said you even meant it being DELETED, which isn't straight forward, yet even when I asked to be cleared on your actual meaning, you sounded so sure of every word and decided giving a mute response. Although, I had to delete my votes to see what exactly the issue was, because the much biasness and high disregard for one's effort on a shallow basis was ad hominem. I don't consider it fair laying off people's honest efforts even to extent of making it a 0%, budget where is the the coops stand on equity? Wasn't  even because the work wasn't done, because a fella lays an insincere comment on the basis of his unfair demands not being met?honestly it's just appalling.

**Comment by dckc** [comment] 2018-06-04 21:23
Yes, well, I made a best effort to get a critical mass of support, and then I proceeded.

There are different definitions of consensus, but the [W3C definition][1] is the one I have worked with the most:
> A substantial number of individuals in the set support the decision and nobody in the set registers a Formal Objection.

[1]: https://www.w3.org/2018/Process-20180201/#Consensus

**Comment by Tonyprisca13** [comment] 2018-06-04 21:35
What are the parameter for trust metric?

**Comment by jimscarver** [comment] 2018-06-04 21:52
Yes we tried the "everybody gets to vote on budgets and rewards" approach and the board decided it got abused. We would prefer a decentralized solution but there is no good model of that working.

In most coops, such as enspiral it takes more than a year for new members to get budgetary voting power at the task/project level. 

If out of 48 trusted members you can get no support from any of them you should just give it up. You are not a cooperator with the active coop members if not one of them will take you on as an apprentice. On the other hand we are taking steps to improve the onboarding so that all new members can be given the chance at apprenticeship.

The bounty system is on a fine line of being accepted or not by the board and Dan works tirelessly to try to keep it working honest. If it were not for him I do not believe the bounty system could have survived this long. 

If you have a proposal you think the board will accept for an alternative to the trust metric, do propose it. 

Complaining without giving a viable alternative with a team ready to implement is disruptive and counterproductive.

Dan may not always be the most agreeable sort but give him a break. I believe he is sincere about helping you to make your issues compelling to the board as something that should be funded. I suggest to take his advice or engage other guides as to what is needed to be funded. You do not have to like his personality or manner. 

If any guide makes an accusation against you that you consider unfair all you need to do is show your work product or otherwise answer the concerns. Getting another guide involved can help resolve disputes.

Do suggest improvement to the system. Find a team to implement the improvements. There is no system to my knowledge that rewards everyone fairly. People tend to disagree about what is fair.

Unless there is some specific proposal I suggest this issue be closed.

**Comment by tcezi** [comment] 2018-06-04 22:37
All members should have at least an apprentice vote until he or she blows it and certification should be based on vote and not on familiarity with some set of persons

**Comment by tcezi** [comment] 2018-06-04 23:11
@jim why should it be closed? The unfairness in bounty trust metric is relatively high compare to d fairness and has to address... everyone deserves reward for work done and not concentrating reward to those with trust metric.

**Comment by jimscarver** [comment] 2018-06-04 23:22
Allan will be entering a proposal to improve the system. Others may be the same. We know the current system is a compromise. Find your team and make it work or the bounty system may be cut off completely.

To repeat. Everyone had a vote and the board squashed it. Now we have a committee of guides including as many people as we can. Anyone being cooperative will have no trouble finding a guide to certify them as an apprentice. Find your team and get working. Complaining does not solve anything. Making the best of what we have is necessary for the system to survive to evolve into something better. People tend to disagree on what is fair and that's okay. The system is decentralized enough that you will be stopped by any small set of guides. You may have to live with some delays in getting started but we are trying to minimize that and seek your help.

**Comment by dckc** [comment] 2018-06-04 23:28
@tcezi writes:
> All members should have at least an apprentice vote until he or she blows it and certification should be based on vote and not on familiarity with some set of persons

How is this different from https://github.com/rchain/bounties/issues/752#issuecomment-394297312 ?
If it is not, how do you suggest we address the question in https://github.com/rchain/bounties/issues/752#issuecomment-394394349 ?

@David405 writes:
> the aim of the issue is to propose a change to the bounty-contract ...

Then something like _democratic voting on bounty budgets and rewards_ would be a better title. The existing title says this is about evaluating the situation, not changing it.

Oh... that gives me an idea... perhaps the seeds of the trust metric should be chosen democratically. Then they would have a democratic mandate much like the coop board does. If anybody like the idea, give this comment a thumbs up or whatever. We could probably use loomio for nominations along with brief statements about / by the nominees, and then a vote. It wouldn't be an official vote of the whole coop membership (unless we do it at the annual meeting), but it might be better than the current situation.

**Comment by jimscarver** [comment] 2018-06-04 23:36
An issue proposing a democratic seed might be worth while. The current system gives the most active and productive members the most say in the system. You may consider that unfair but I think is was a stroke of genius to answer the boards concerns in a simple manner. I bow to our most productive members and am grateful to them that we have anything at all. I worry a bit that elected members may not be knowledgeable as active members and may not act in a manner the board will approve of. But it is certainly worth trying.

**Comment by barneycinnamon** [comment] 2018-06-04 23:39
If part of the goal of the coop is to experiment with ways to get distributed groups of people working together productively, is there any reason to consider distributing some part of the available bounty budget to systems governed by different proposed rule sets? Contributors can choose which bounty system they want to participate in, and at the end of some period, some set of metrics can be prepared to compare across the different systems. I am thinking things like: number of people who participated, total rewards distributed, and some summary of output produced. Maybe we could survey members who participated in a given bounty instance to rate it on ease of use, how effective they thought it was, etc. The point wouldn't be to pick the best system but to learn about things that were and weren't effective in different schemes.

**Comment by dckc** [comment] 2018-06-04 23:42
Interesting idea in theory, but given the training challenges involved in following _one_ set of rules, I wonder if it's feasible.

A somewhat related suggestion I heard from Greg M. a while back is a sort of tree of budgets. It would most likely be split by function area (aka labels).

**Comment by barneycinnamon** [comment] 2018-06-04 23:48
If I got to design one bounty system scheme, it would be something like the trust metric seeded by function area SOWs. Whatever power is authorizing SOWs would approve budgets and sets of tasks (specific or vague depending on the function area and the person's qualifications and stated goals). It is not decentralized with respect to authorizing the initial trust seeds and area budgets, but there could be a mix of job description / RFP posts from top down and proposals / issue ideas from the bottom up. If a bottom up idea fit into an existing guide's purview, they could sponsor the issue. This would make a more explicit connection between the goals of the leadership and the contributions of the members, and it would make accountability easier, because accountability and trust would flow together.

**Comment by jimscarver** [comment] 2018-06-04 23:48
I object to budgets by area that squash or delay necessary and worthwhile projects.

I suggest a liquid democracy where members can have their vote delegated to representatives on issues where they do not themselves vote. If I trust Kit and assign him as my representative then he would get his and my vote on issues I do not vote on. I expect the weighting of votes that results would be very close to the current trust metrics but who knows until we try it. It might centralize voting even further which is an outcome that concerns me.

**Comment by dckc** [comment] 2018-06-05 00:01
We have an issue on delegate / proxy voting (#484) I recently closed it with some regret... 

> I don't see myself getting to this any time soon.
>
> Anybody else who wants to work on it is free to re-open it.

The liquid democracy idea is something that has interested me for years. I'd love to see it happen.

**Comment by tcezi** [comment] 2018-06-05 00:06
@dckc are there any parameter to justify the current trust metric?

**Comment by Viraculous** [comment] 2018-06-05 04:08
I personally appreciate the collective and individual effort of the RAM in making attempts to checkmate bad actors and to ensure that the bounty system is working towards the vision of the RChain community. I wish to air my view on this issue.
With regards to this issue, first of all, I will like every member to see the issue from a functional point rather than critical. I can boldly say from my view that, this issue is functional in that it is aimed at bringing out the flaws of "Trust metric system" and thus, making room for advancement for a better governance. 
Secondly, concerning the "Trust metric system"; should it be put away? No, the reason is that it was implemented this month and therefore, is still in some sort of probation. What about the "Trust metric system"? In my opinion, non-active participants of an issue,  should not have the power to decide the percentage vote on work done by a set of people whether with "Trust metric" or not. This is because they are myopic about the measure of work done by each active participants of an issue. Also concerning budget, the "Trust metric" can play but it should be limited to guides of a particular issue.  Power to vote on a budget should be handled by label guides to issues within the same category. The label guide should be able to resolve issues within their span of control, where the issues prove tough, then a general consensus can be reached to resolute the issue.
Thirdly, there have been upheavals about the parameters to justify the "Trust metric". The question that comes to my mind is, on what basis should I trust the trustees of the current "Trust metric"? This is due to some concerns. Man is by nature self-seeking and would always want his interest first represented in his endeavor and is influenced to biased in judgment and preference towards persons. Can people who represent their interest first, be worthy of trust especially on financial matters? Certainly, to some degree at all points, individual's interest must play but the aim is to keep it at a very minimal rate. Not minding, people would bear better if individuals representing them were elected democratically than without the consent. At this point, I suggest that members of the RAM should be able to vote in those who deem it fit for trust metric and also, the tool certification should be clearly stated I.e on what basis, should a person receive the trust metric. For now, I rest my case.

**Comment by tcezi** [comment] 2018-06-05 08:48
@dckc i mean what criteria/rule used to justify those 46 person as trusted persons

**Comment by Keaycee** [comment] 2018-06-05 14:14
Well, some coop members feels like the power to place budget and allocate rewards among them self has been deprived. They also think the system is no longer decentralized like it was on the first quarter of the year. They also think that the trust metric is very biased.
The trust metric just began and has only been applied in month of May and it seem very difficult for coop members to get their reward for work done. 

@David405 comment

> @TrenchFloat, you voted 5% for Makys on #672 but I don't see her input, maybe you might want to explain this, also, @jimscarver voted 5% for @ICA3DaR5 ON #681 where there was no input from @ICA3DaR5 and 25% for @nonnykul who is the main actor on the project. How do we co-relate this?

I observed that the problem is voting of reward. The rewards should be done among the collaborators or the participants of the issue. @David405 on his comment above, The votes reward awarded to @makys  and @ICA3DaR5 wasn't on merit because they did not participate. 

Secondly, members who has SOW don't claim reward awarded to them by collaborating or participating on an issue, i suggest giving those reward to other supporting collaborator or participants.

Thirdly, the trust metrics do not know the efforts of work done by other participant or collaborators of a particular issue. I do not see it fit for the trust metrics to allocate reward to the collaborators or participants on an issue, it should be done by the collaborators on how they see fit. 

The major reason of the trust metric is to cub the abuse of high budget placed on an issue. However, the slashing method has a way of doing that directly. When a budget is outrageously high compared to the work done, the slashing method can be used to adjust the budget appropriately. 

### PROPOSAL
**I suggest the trust metric should only imply on only the budget votes alone.**

**I suggest a monitoring committee, that will serve as a watchdog for every budget placed on any issue on a monthly basis.**

**Slashing of budget should be aim at resetting the proposed budget to the supposed or appropriate budget of the issue. Rather than depriving coop members of reward based on work done, that can be very discouraging.** 

**I suggest coop members be given privileged to place budget on the reward app. It can be 2 trust metrics members and 1 member from any rating.**

**Comment by jasoncruzzy** [comment] 2018-06-05 15:13
@Keaycee  your proposals are great and considerable I made similar suggestion earlier, The 'Trust metric' should have the powers to vote and adjust budgets only, while collaborators and participants should vote on the approved budget  on each issue.
 Hence the obvious majority of RAM's are clamouring  for a review/restruct on the current 'Trust Metric system' the board should kindly consider our appeal. This current system could whittle down the motivation on already existing RAM

**Comment by Pionelle** [comment] 2018-06-05 15:42
Well said! 

    On Tuesday, June 5, 2018 3:14 PM, Keaycee <notifications@github.com> wrote:
 

 Well, some coop members feels like the power to place budget and allocate rewards among them self has been deprived. They also think the system is no longer decentralized like it was on the first quarter of the year. They also think that the trust metric is very biased.
The trust metric just began and has only been applied in month of May and it seem very difficult for coop members to get their reward for work done.@David405 comment
@TrenchFloat, you voted 5% for Makys on #672 but I don't see her input, maybe you might want to explain this, also, @jimscarver voted 5% for @ICA3DaR5 ON #681 where there was no input from @ICA3DaR5 and 25% for @nonnykul who is the main actor on the project. How do we co-relate this?
I observed that the problem is voting of reward. The rewards should be done among the collaborators or the participants of the issue. @David405 on his comment above, The votes reward awarded to @makys and @ICA3DaR5 wasn't on merit because they did not participate.Secondly, members who has SOW don't claim reward awarded to them by collaborating or participating on an issue, i suggest giving those reward to other supporting collaborator or participants.Thirdly, the trust metrics do not know the efforts of work done by other participant or collaborators of a particular issue. I do not see it fit for the trust metrics to allocate reward to the collaborators or participants on an issue, it should be done by the collaborators on how they see fit.The major reason of the trust metric is to cub the abuse of high budget placed on an issue. However, the slashing method has a way of doing that directly. When a budget is outrageously high compared to the work done, the slashing method can be used to adjust the budget appropriately.
PROPOSAL
I suggest the trust metric should only imply on only the budget votes alone.I suggest a monitoring committee, that will serve as a watchdog for every budget placed on any issue on a monthly basis.Slashing of budget should be aim at resetting the proposed budget to the supposed or appropriate budget of the issue. Rather than depriving coop members of reward based on work done, that can be very discouraging.I suggest coop members be given privileged to place budget on the reward app. It can be 2 trust metrics members and 1 member from any rating.—

**Comment by dckc** [comment] 2018-06-05 15:44
@Keaycee writes:

> I suggest the trust metric should only imply on the budget votes alone.

I don't see how that's consistent with the board's Apr 6 decision (specifically steps 5, 6, and 7 of the [Task Approval process][1] regarding Project Bid Submissions); I trust you'll weigh in on #616 as to whether you think it is consistent or whether you're asking the board to reconsider their decision.

> Slashing ... depriving coop members of reward based on work done, that can be very discouraging.

Yes, well, the whole point of slashing is to discourage unacceptable behavior.

[1]: https://github.com/rchain/bounties/wiki/Task-Approval

**Comment by kaka56** [comment] 2018-06-05 15:52
@jasoncruzzy  suggested
>The current trust metric reward system is good but rather than vote on issues directly, the persons with trust rating should vote on budgets for each issue and in respect to the performance of tasks and targets 

>The voting for rewards on each issue should be done by the 'creator' of the issue and its collaborators with the 'creator' of the issue having veto powers over the collaborators
If we put this into consideration it will ensure 'fairness' and less of human factors.

I personally agreed with @jasoncruzzy . The trust metric system needs to be balanced where by those with trust metric should be the one to place budget vote  and allow the creator of the issue and it's collaborators to place the reward vote. And if the the collaborators of the issue is less than three, some one with trust metric should follow the reward pattern of the 'creator' of the issue.
@lapin7  you placed a budget vote of $900  on [661](https://github.com/rchain/bounties/issues/661) and rewarded 50% to the main worker alone. What happened to the remaining 50%? An explanation is needed.

@David405 comments
>> @TrenchFloat, you voted 5% for Makys on #672 but I don't see her input, maybe you might want to explain this, also, @jimscarver voted 5% for @ICA3DaR5 ON #681 where there was no input from @ICA3DaR5 and 25% for @nonnykul who is the main actor on the project. How do we co-relate this?

**Comment by allancto** [comment] 2018-06-05 15:55
@Keaycee thanks for your comment and Proposal above. 

@dckc @kitblake @lapin7 I am wondering why our current system is designed for voters to separately vote on overall budget and then on individual contribution. As an outsider looking at a particular issue it makes sense to me to evaluate the overall impact of the work product, but I'd suppose that dividing up the reward would be primarily a job for the team to decide. Would it make sense for the issue statement to include specific allocation of reward to each contributor, and voting to be on the overall budget? Mechanistically this would probably require specific fields within the issue statement to generate the appropriate reward for each contributor (more work programming but less work voting).

**Comment by dckc** [comment] 2018-06-05 16:10
@tcezi writes:
> what are the criteria used to justify those 46 person as trusted persons?

Though you don't follow [best practice][1] in saying where you looked for the answer, I'll give you the benefit of the doubt that you read https://github.com/rchain/bounties/wiki/Trust-Ratings and #375 carefully and you still don't see an answer to that question.

The answer is this part of the wiki page:

> The next step is automatic evaluation of the trust metric. There is a set of users from which all trust flows ... . The evaluation itself is essentially a network maximum flow solver, for which nice efficient algorithms exist. The people reached by the flow are those accepted by the trust metric. With the three levels, the maxflow is computed three times: once with just the Master certs, once with Master and Journeyer, and once with all three.
> 
> Like all examples of a CapacityConstrainedFlowNetwork, the AdvogatoTrustMetric is robust against noisy or malicious cert data.

and #375 includes pointers to my slides and an Raph's academic style paper.

If you're the sort that prefers to read code, the code we're running is https://github.com/dckc/rchain-dbr (currently cac6173 ). In particular, see  [net_flow.py](https://github.com/dckc/rchain-dbr/blob/master/net_flow.py) which I borrowed wholesale and [class TrustCert in social_coding_sync.py](https://github.com/dckc/rchain-dbr/blob/master/social_coding_sync.py#L464) which calls it.

[1]: http://www.catb.org/esr/faqs/smart-questions.html#before

**Comment by tcezi** [comment] 2018-06-05 17:48
@tony am sorry it was a mistake. Wanted to address your comment.

**Comment by Pionelle** [comment] 2018-06-05 23:00
@dckc On the with-holding all of my rewards based on irregularities on this #653. I find that a bit unfair, but if it is the rule. It must stand then, shouldnt it? I only found of this today and I was left confused since the other works were unrelated to this.
But then you mention what had to be done. I also would suggest that an alternative to what is stated be provided by those with the power to do so.
But it still came to me as a surprise that I had to be punished even for the good works I had done in other areas of RChain.
We need the rewards to keep thriving to meet the marks set for us. And making people feel punished is never a good solution to any work place problem

**Comment by jimscarver** [comment] 2018-06-06 12:31
I agree with @allancto that participant reward votes should count for observers working on issues. That will simplify the task for guides greatly as they would only need to vote on rewards for certain cases. The only issue is how compete the issue is and if the full budget rewarded by the team represents the actual work done.

@dckc I agree with @Pionelle that withholding rewards on other issues because of disagreement on one issue is unfair and wrong. Work on each issue is a separate issue.

**Comment by pmoorman** [comment] 2018-06-06 14:39
@jimscarver @Pionelle but isn't that the whole idea of slashing: that you have actually something [significant] to lose for bad behavior?

If people misbehave and abuse our trust, that should have more severe consequences than just not getting what you ask for. Otherwise there's nothing to lose from always asking for ridiculous rewards. 

**_The problem here is that @Pionelle is claiming tokens for bad work. Not that this governance system is broken!_**

**Comment by dckc** [comment] 2018-06-06 14:40
Slashing is not based on disagreement. It's based on unacceptable behavior, as judged by a quorum of the community. And having consequences beyond one issue is the whole point. You have to be fair everywhere or your whole "stake" (reward) for the pay period is at risk. (If there is more discussion on this point, I would prefer to have it in the slashing issue, #261).

As noted in #653, I have removed two of my slashing votes because the respective unfair votes were removed. The process seems to be working quite well, in my experience.

**Comment by Pionelle** [comment] 2018-06-06 19:19
@pmoorman You could be correct.
And you maybe a little bit incorrect. Because of in doing the work, we subjected the pre-published work to inspection from other equally good workers. 
**And if in the conclusion, that opening up our works to scrutiny, and whatever the result of that was, is wrong.** Then the whole process may have been easier if we had avoided any standards and went ahead to claim rewards. Which is wrong.
Whatever the outcome was, doing the right things comes first. Lastly, I do not support having a punishment feel in the work place, and extending such inhumane treatment to a member's other work.

**Comment by pmoorman** [comment] 2018-06-06 19:58
@Pionelle I don't understand what you're talking about.

Better explain in #653 why those tokens you're claiming are deserved. That's the root problem, not the slashing system.

**Comment by Pionelle** [comment] 2018-06-07 12:49
@pmoorman The issue has been resolved. The review never happened. 
And I had never acted entitled to whatever reward there was.
 The issue still remains that extending ''punishment'' to a member's other rewards seems unfair.

**Comment by dckc** [comment] 2018-06-07 16:15
As I said above on Jun 3, the most straightforward change to the existing system is to tweak the parameters for the expected number of masters, journeyers, and apprentices. Based on discussion in yesterday's RAM meeting (#758) and chatting with @jimscarver today, I did so: https://github.com/rchain/bounties/issues/375#issuecomment-395478315

  - `8ed0ddf` 45 isn't enough apprentices; try 100

**Comment by jimscarver** [comment] 2018-06-23 15:30
It should not be easy to discredit a person. Caring for the individual is a coop ethic.  The current slashing rules seem worse than the the chinese social credit system https://www.facebook.com/NowThisFuture/videos/vb.1010847105623136/2164563946918107/?type=2&theater

**Comment by lapin7** [comment] 2018-06-24 08:38
I suggest to slash per issue. Then the effects are less drastic

**Comment by dckc** [comment] 2018-06-25 22:52
This has been a useful discussion, but I don't see anyone taking the ball to follow up, so I'm closing this. I supported the $400 budget suggestion with a vote. If you seek a reward, add a reward vote for yourself and I'll consider matching it.

Feel free to re-open this issue if you see more progress to be had.

@Valentine-Mario it's not clear to me why you assigned yourself, but I don't see any progress in the last three weeks.

## Slashing

@lapin7 I don't see any new information since last time that suggestion was made and rebutted by myself and @pmoorman :

> having consequences beyond one issue is the whole point. ... -- https://github.com/rchain/bounties/issues/752#issuecomment-395092855

@jimscarver I don't think getting a quorum of 10x weight is too easy. I don't see any cases where 10 has been too low. If you disagree, I suggest you follow up in #261.

## Number of apprentices etc.

Note that I recently opened:
  - how many apprentices, journeyers, and masters should there be? Operations bounty-contract #785

**Closed by dckc** 2018-06-25 22:52 UTC
Labels: Discussion, Voting, bounty-contract
