### ISSUE TITLE
REFORMS IN THE BOUNTY PROGRAM; What is the direction?

### ISSUE THREAD

**Issue by azazime** [rchain/bounties#982] opened 2018-09-26 11:04 UTC
With all the current reforms which has been on-going in the past couple of weeks, there is a need for clarity;

* Is the Bounty Program still a decentralized system and how does these new reforms support it? If so, why is there just three(3) members with trust rating and what is the plan moving forward?

* There are complications in navigating the bounty system for contributors which has not been made any easier by the new reforms? E.g How do a new member get sponsors for his work if he barely knows who to meet or how to go about it?

* Market Price Cap as it pertains to payment of Rcontributors; what exactly is the board resolution on this issue?

* How effective are the new reforms in the bounty system?

### Benefit to RChain
BOUNTY REFORMS; clarity for RAMs contributing to RChain through the Bounty Program

### Budget and Objective

*Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.*
_Estimated Budget of Task:_ **$(???)

### Legal

_Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws._

Cc @dckc @deannald @David405 @ddayan @zsluedem @jasoncruzzy @tucsonblockchain @jimscarver @casanwugo @Ojimadu @kitblake @philipandri002 @kovmargo @allancto

**Comment by jasoncruzzy** [comment] 2018-09-26 13:33
1) Not elaborate: @ddayan how does having just 3 certified trust metric members makes the process less decentralized??, or has the voting process for the bounties changed??

3)Market Cap price: Talked about the Rhocs/Dollar payment, here is a 

> In full context from the January 25 Board Meeting Minutes: 

WHEREAS, the Cooperative wishes to incentivize its employees, contractors, and other
members to choose to accept RHOC/REV in exchange for work provided to the Cooperative.
RESOLVED, the policy of the Cooperative shall be that the price of RHOC/REV tokens
for the purpose of calculating the quantity to be paid to employees and contractors of the
Cooperative shall be calculated using a 30 day market weighted average price calculated on the
day prior to payment, or the prior day’s listed price on Coinmarketcap.com, whichever is lower.
Further details will be in the Compensation Committee’s policy for the Cooperative.
FURTHER RESOLVED, the Compensation Committee shall control revisions of this
policy going forward, and to effect a change to this policy the Compensation Committee shall
submit a written proposal for an amended policy for Board approval.


https://github.com/rchain/board/blob/master/2018/01-25/Meeting%20Minutes.pdf 

👆 This has been a debate for some time now, and it keeps coming up. Because from my understanding of that, they said we should either use a 31day old market Cap or a previous day market cap but 'WHICH EVER IS LOWER' but it seems we only use the 31day old Market Cap...Have an idea if the board has reviewed this??

4. New Reforms: @ddayan do we have a 'google docs' where this reforms are outlined, because I only see this reforms on 'Discord' as comments, which only makes the system much more complicated for enthusiastic NEW members?

**Comment by ddayan** [comment] 2018-09-26 14:18
@jasoncruzzy 

1. People are more depended on sponsorships than on the certified trust metric members. It's extremely unlikely that the certified members will down vote you if you have a sponsor. Also those trusted individuals were picked by the board which we as a coop elected so the process of electing them was fairly decentralised.

2. As I said before I believe that the compensation committee will discuss it.

4. I don't think there's a google doc.

**Comment by tucsonblockchain** [comment] 2018-09-26 14:54
System is highly centralized, I'd rather work within a 2 party failure

**Comment by dckc** [comment] 2018-09-26 19:09
#969 covers the question of USD/RHOC rate for rewards.

The rest of this issue is a duplidate of #783, no?

**Comment by azazime** [comment] 2018-09-26 20:56
No @dckc

**Comment by dckc** [comment] 2018-09-26 21:15
Which part of the issue is not subsumed by #783 and #969?

I can elaborate on how this _is_ a duplicate:

> ... why is there just three(3) members ...?

because the executive committee chose 3 members of the TAC and as explained in #783, those three TAC members are raising the bar for delegating, based on feedback at and since RCon3

> ... How do a new member get sponsors for his work if he barely knows who to meet or how to go about it?

As explained in #783, it's important to help each other find sponsors for good work. I am making an effort to do so.

> Market Price Cap as it pertains to payment of Rcontributors; what exactly is the board resolution on this issue?

It's quoted in full in #969.

> How effective are the new reforms in the bounty system?

The new reforms are the subject of #783.

**Comment by tucsonblockchain** [comment] 2018-09-27 16:20
This is far beyond Mother May I. This is not self determination, this is not self sufficiency, this is not self governance. We already proved that point and it all got swept under the carpet and for that it clearly meets the definition of centralized, certainly doesn't meet or even come close to the criteria of decentralization. We tried offering solutions and even elected a delegate (Andrew) and it basically was ignored. We tried the sociocratic democratic method and rightfully so, and it got ignored. And then mid stream, it seemed they wanted to go another direction, top down, from "the board". This is like a kingdom, not a common people determining destiny. This is like some corporate thing claiming to be decentralized and for the members, when it just turns into some Rholang do as I say. The voting and collaboration thing is a bottleneck. Clearly the spinoff needs to be competing methodology and put that up against this decentralized process. The mother may I nature of this voting system and the talk alone is centralized, but it's not walking the walk.

**Comment by azazime** [comment] 2018-09-28 09:18
@dckc I believe my question; How effective are the new reforms to the bounty system is clear enough? What seems to be confusing is your reply...am trying to understand how effectiveness in this case is subject to #783 ?? Please can you explain what you mean, thanks

**Comment by jimscarver** [comment] 2018-09-29 14:27
Identifying sponsors may be a difficult process. I suggest we employ endorsements 👍 and objections 👎 to cooperatively indicate sentiment along with comment we enter on issues. We might use other reactions additionally like 💯 or 🥇 to indicate degree of support.

**Comment by kovmargo** [comment] 2018-10-02 09:05
Hi guys! A lot of questions arise in relation on new reforms and on the eve of voting.  I see no better way than asking questions  here:
1.  Will continue to vote for the issues that we open/close in September? 
2.  From which date for open-issues sponsors will be needed? For  example,  issues  that were open after 19 Sep should have sponsors
3. There are 9 people with the rating at the [rewards](rewards.rchain.coop) not 3 as it were describe above.  Why? What is their role now? Is there a connection with sponsors?
4. Is there a list of all departments and the people who head them and those who can sponsor? I will explain. For example, I want to do smth valuable for coop and first I need to find the sponsor. What should be my steps? 
@dckc "As explained in #783, it's important to help each other find sponsors for good work. I gave an example of how I am making an effort to do so." 
Sorry, I read all #783 and didn't find clear steps how to find sponsors. 

I would be very grateful to receive specific answers.

**Comment by azazime** [comment] 2018-10-03 23:03
@kovmargo I believe your questions were answered in issue #783 ??

**Comment by dckc** [comment] 2018-10-10 03:36
Every question raised here has been in scope for #783 or  #969. This is clearly a duplicate.

**Comment by dckc** [comment] 2018-10-14 05:53
If you want to reopen an issue, be sure to explain why.

**Closed by dckc** 2018-10-14 05:53 UTC
Labels: Discussion, Help Wanted
