### ISSUE TITLE
Negotiate bounty budgets and rewards in RHOC rather than USD

### ISSUE THREAD

**Issue by philipandri002** [rchain/bounties#904] opened 2018-08-15 08:06 UTC
Lets Talk About Rhoc: @jimscarver @dckc @David405 @deannald @casanwugo @pmoorman  @allancto @Ojimadu @azazime @AyAyRon-P @ICA3DaR5 @Kitblake @pavlos1851 
Estimated Budget of Task:_ $[TBD]
Timeframe: Month of August
Measure of completion: steps are been taken to address the issue: 

There is a saying that "A workman is worthy of his wages". On that regard, I have decided to create this issue to address the present state of Rhoc and its depreciation in value when exchanged to USD. In the past 2 weeks, Rhocs has continued to trend downwards with its figures in red. The market has yet again lost some more significant value this week. 

As RAMs, even though we get rewards for the tasks done for the coop, i dear say we are not actually getting true value that reflects the effort we put in. In the month of May, I completed tasks which was negotiated in $(Dollar) yet payments made in Rhocs. I got $585 as a true reflection of my work done, but when paid in Rhocs, value was reduced to $376, and in a space one week - $202.

My point in summary is this; If I do a job worth $40 and it was negotiated in that value, why pay me with a lesser value?

IMO, To make the bounty system fair, I suggest that all rewards in Bounties be negotiated in Rhoc since that's our payment currency and not dollars. This way, everyone knows exactly what they deserve for their effort and that's what they truly get.

Thanks

Frank..

**Comment by AyAyRon-P** [comment] 2018-08-15 13:40
Hi @philipandri002 

I understand your frustration and know how you feel. When work is done, work is done and we all deserve to be fairly compensated for it. 

I've lost over 32% of the value in my portfolio in the past 3 weeks and that's including making money on short trades - would've been closer to 55% otherwise. This is the nature of the beast and we can't predict only speculate which way it will go. 

We are compensated in USD based on the value of the RHOC at the time of payment. Could you clarify what you mean by being paid in a lesser value? RCHAIN payouts are done on a market30 average which is the most fair to everyone. Your value isn't any less and it's not RCHAIN who is saying your efforts are now worth less. Let's say the day the pay period closes, you worked on an issue worth $100 and the value of RHOC is at $1 - so you get 100 RHOC, if the next day the RHOC goes $2 your, your $100 is now worth $200 - no complaints there, right? But if it goes the other way and the next day the RHOC hits $.30, your $100 is now worth $30. Is it RCHAIN's responsibility to compensate you for the drop in market value? The short answer is no, they are not. That's the risk and reward in all of this.

**Comment by tucsonblockchain** [comment] 2018-08-15 14:26
A workman is worthy of his wages, and should be able to buy all Big Macs or buy silver on this dip, but one cannot access the wages to buy on the dip, missing great opportunity. This opportunity cost is as costly as the tax liability as is the down market in crypto as a whole. A worker should have the right and ability to buy diapers for their baby before they get crappy. The entire invoicing process must be abolished and has been motioned by way of vote, giving ample notice for others to show up, with meeting August 18th, for right to form delegate(s) and time for comments, and for vote 48 hours later. https://docs.google.com/document/d/1eREvzNJxrSCkJaZtFE4p28FPYJJyzfwqfhilX4o0Hfo/edit?usp=sharing

**Comment by AyAyRon-P** [comment] 2018-08-15 14:41
@JoshOrndorff so the value of the issues would no longer be in USD but RHOC? That seems backwards and again makes no sense why we would do that. What is the benefit to valuing projects in RHOC? There is NO difference. Take my example again, if you value an issue at 100RHOC and the RHOC is worth $1 your issue is worth $100, but if the market fluctuates positively or negatively between the time of approval to the time of processing why should RCHAIN be held accountable for the instability of the market?

**Comment by AyAyRon-P** [comment] 2018-08-15 14:48
@tucsonblockchain why is it the responsibility of RCHAIN to cover market losses between approval and payment time? Neither you nor @JoshOrndorff have explained why you feel this way. If you wanted to have funds available for the dip, watch the performing oscillators, look at the marketing analysis, review the averages, all of that information that is free that could have allowed you to participate in buying tokens during this bear market. 

If the price of goods goes up in your grocery store/market, do you go to your work/day job and tell them "Last week I could afford this but now it costs more, I need a pay increase or be compensated for the difference." That's not how the world works.

**Comment by dckc** [comment] 2018-08-15 18:39
I see in notes from today's RAM meeting (#901) that the relevant policy is a board decision about paying invoices. So this isn't a **bounty-contract** issue. This is **Operations**.

Note that CONTRIBUTING.md doesn't mention votes being in USD. [Creating an invoice](https://github.com/rchain/bounties/wiki/Creating-an-Invoice) is one of the more relevant bits of documentation.

The ISSUE_TEMPLATE was also not followed, so I'm marking this **needs-SMART-objective**.

**Comment by dckc** [comment] 2018-08-15 18:40
updating assignments based on notes from #901 meeting:

> Ojimadu and Allan will make sure the 1/25 board resolution based on the market 30 system is being followed in practice.
> Andrew and Allan will contribute to the discussion in issue #904.

**Comment by tucsonblockchain** [comment] 2018-08-16 17:42
TucsonBlockchain:Today at 10:29 AM
2018-08-16 First order of business is at 1:55 PM (Eastern Time) - or 5 Minutes prior to Work Study (CoLab). It was discussed at the previous meeting on the 14th of Aug that Andrew was to contact Discord to call to meeting by way of Notice and establish a delegate(s) and a 48 hour period from time of meeting to discuss the issue of invoicing and prompt pay. Brent was unable to determine Andrew’s handle in discord nor saw the Notice. Brent delegated himself and served the Notice in the #general room and established the time of 1:55 PM to establish the meeting as discussed, with a 48 hour voting period from time of meeting as discussed in our notes. It is necessary to establish the delegate(s) and Notice has been served in the process, as we so have done via the Sociocratic process. Notice has been served to bring greater attendance to the meeting. The Zoom link of https://zoom.us/j/6853551826?pwd=&status=success has been provided in Discord and we can now establish the first order of business as discussed in the last meeting. <---serves Notice for attendance.

**Comment by allancto** [comment] 2018-08-16 19:28
@Ojmadu and I read the board resolution of 2018-01-25 minutes for usd-rhoc conversion is quoted below. The process for modifying this would be for the Compensation committee to submit a new proposal to our board. Since a blanket change might affect many people outside the bounty system, it would likely require a great deal of review and discussion to do that. 

> the price of RHOC/REV tokens for the purpose of calculating the quantity to be paid to employees and contractors of the Cooperative shall be calculated using a 30 day market weighted average price calculated on the day prior to payment, or the prior day’s listed price on Coinmarketcap.com, whichever is lower


I see that the issue title has already been changed to "Negotiate bounty budgets and rewards in RHOC rather than USD". In my opinion that would be an easier change to make because it might affect only the bounty system within our Cooperative. 

If the majority of our contributors are in favor of doing this I would agree to look into it further. For me, my personal perspective is that I live simultaneously in two economies- usd and rhoc; both are important to me and I keep balances in both. So for me it would make sense to budget and reward issues in rhoc. Whether this is an issue important enough to focus on now, I'm not sure, let's see what the consensus is. 

-@allancto

**Comment by azazime** [comment] 2018-08-16 19:54
In as much as I feel indifferent about the idea of negotiating rewards either in rhocs or USD as it could swing either way depending on crypto market value as at the time of payment, I feel we could have a more better process of payment where we could maybe do away with the invoicing process?

**Comment by tucsonblockchain** [comment] 2018-08-16 20:50
I second the motion to do away with the invoicing process in it's entirety.
But we are going to discuss as an order of business and as notified in work
study group.

**Comment by ICA3DaR5** [comment] 2018-08-16 22:29
@azazime @tucsonblockchain 

That's impossible, since the invoice process is a legal requirement.

cc @allancto

**Comment by azazime** [comment] 2018-08-16 23:03
@ICA3DaR5 the goal here is to improve the process/time of payment as it affects collaborators

**Comment by tucsonblockchain** [comment] 2018-08-16 23:10
Here here.

**Comment by tucsonblockchain** [comment] 2018-08-16 23:16
Welcome Andrew or @azazime as the delegate voted on by peers to represent RAMs, to straighten out the process and to stand for economic freedom and choice, that which blockchain can and will bring. This is an important first step. Please support him in his efforts and look at what he will do to advance the cause. We supported him by way of vote and established a budget and gave him full legal authority as delegate. That's right. That's what the coop members did.

**Comment by ICA3DaR5** [comment] 2018-08-17 23:00
Discussion on issues #904 and #910: https://youtu.be/tHzuVqEyMZ4

**Comment by ICA3DaR5** [comment] 2018-08-20 01:50
Some more discussion on issues #904, #910 and #912

**Comment by ICA3DaR5** [comment] 2018-08-23 21:48
> The price of RHOC/REV tokens for the purpose of calculating the quantity to be paid to employees and contractors of the Cooperative shall be calculated using a 30 day market weighted average price calculated on the day prior to payment, or the prior day’s listed price on Coinmarketcap.com, whichever is lower.

My calculation tells me that the second rule hasn't been followed.
It seems that we are always getting paid with a 30 day market weighted average.

I am talking about this part: 

> ...or the prior day’s listed price on Coinmarketcap.com, whichever is lower.

**Comment by Tonyprisca13** [comment] 2018-08-24 06:05
The  board resolution is not been followed for the last 2months.

**Comment by allancto** [comment] 2018-09-07 02:13
@philipandri002 as i understand, the purpose of this issue is to denominate rewards in rhoc. What progress have we made towards that? 

Thanks! -allancto

**Comment by philipandri002** [comment] 2018-09-07 17:26
@allancto Okay... let me give a quick response. I know that I was able to raise some level of campaign that even though  the issue of rewards in rhocs has not been agreed on, you will agree with me that work is been done towards making that possible as seen in #910.
Issue #912 I guess was also as a result of the campaign to get payment of rewards in a more quicker and advance approach

Thanks!

**Comment by kitblake** [comment] 2018-09-08 13:18
Can we close this @philipandri002? Doing so, reopen if needed.

**Closed by kitblake** 2018-09-08 13:18 UTC
Labels: Discussion, Operations, needs-SMART-objective
