### ISSUE TITLE
Translate ''Resonate and lifeID collaborate'' blog post to French

### ISSUE THREAD

**Issue by Pionelle** [rchain/bounties#623] opened 2018-04-25 22:32 UTC
### For all issues
[Keep italic labels, replace brackets with answer]

*Describe how the building and implementation of this task will benefit the RChain Membership or the RChain blockchain:* 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

*Estimated Budget of Task:* **$[200]**  \
*Estimated Timeline Required to Complete the Task:* **[2 days]**  \
*Measure of Completion:* **[20%]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [ ] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [ ] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in (the target language)
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

bonjour, c'est mon premier travail

**Comment by Pionelle** [comment] 2018-04-25 22:33
J'ai payé l'adhésion, mais je n'ai pas pu être vérifié.

**Comment by lapin7** [comment] 2018-04-25 22:50
Essayez de faire un RDV avec @makys

**Comment by makys** [comment] 2018-04-25 22:58
@Pionelle Nous pouvons faire votre vérification. Envoyez-moi un message sur Discord @makys

@lapin7 Merci

**Comment by Pionelle** [comment] 2018-04-25 23:03
https://docs.google.com/document/d/1slQ1_He2KSx0Gh0HN3w7v6PopMHa1Jr6wQs7S0TdGjM/edit?usp=drivesdk&ouid=112243679794038364949
Fait le premier brouillon

**Comment by Pionelle** [comment] 2018-04-25 23:03
@lapin7  je ferai une fois de plus

**Comment by Pionelle** [comment] 2018-04-25 23:14
@makys aha! 
Oui, je suis content que tu sois là. Mais maintenant c'est tôt le matin. Je vais vous envoyer un après-midi. Je vous remercie

**Comment by Pionelle** [comment] 2018-04-25 23:53
Je préférerais être formel. J'ai un autre travail que je fais, dans 7 heures, avec le travail du jour pour moi.

**Comment by Pionelle** [comment] 2018-04-26 11:56
Merci, dac
    On Thursday, April 26, 2018, 12:21:36 AM GMT+1, makys <notifications@github.com> wrote:  
 
 
@Pionelle
Si vous avez quelques minutes, nous pouvons le faire. C'est un processus rapide.

**Comment by BelovedAquila** [comment] 2018-04-27 14:50
@Pionelle Agréable vous voulez travailler sur le projet de traduction de la communauté, être un membre RAM  pour collaborer efficacement S'il vous plaît ☺ 
- [x] Join RChain Coop by signing up for membership
- [x] Join https://groups.google.com/forum/#!forum/rchain/join to get access to documents of RChain. rchain@googlegroups.com 
- [x] fill out form RAM registration https://docs.google.com/forms/d/e/1FAIpQLSecwGUVFNx_Xa_Qsw5bxLnaKstPS8kQnfrUGqpuf22rLDteDg/viewform
- [x] Join github/rchain/bounties in order to contribute
- [x] watch video https://www.youtube.com/watch?v=vcIZSZmpO9E&feature=youtu.be
- [x] read RChain Decentralized Bounty Program https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md
- [x] Claim your reward with form Declaration https://docs.google.com/forms/d/e/1FAIpQLSe3ZxbwVL_yQZ7DTSw9V5VZod1U9XeZxDMZB7jupRCnx79erQ/viewform
Should have done a more impressive work on that, maybe against another acticle, but nice article.

**Comment by truffard** [comment] 2018-04-29 14:13
bonjour puis je travailler sur ce projet de traduction?

**Comment by lapin7** [comment] 2018-04-29 21:45
Qu'est-ce que tu pense toi même?
Est-tu d'accord avec les autres traducteurs Anglais-Français?
Enfin, change le première message de cet issue? Pcq c'est seulement un copie du template.

**Comment by BelovedAquila** [comment] 2018-04-29 22:45
@truffard and @Pionelle Que diriez-vous de collaborer sur des traductions françaises pour la coopérative ensemble?

**Comment by truffard** [comment] 2018-04-29 22:51
@BelovedAquila oui bien sur sans souci

**Comment by BelovedAquila** [comment] 2018-04-30 06:31
@truffard Très bien, êtes-vous sur l'un de nos canaux de médias sociaux? Rencontrez-moi sur la discorde ou le télégramme @BelovedAquila

**Comment by ICA3DaR5** [comment] 2018-05-18 21:04
This is the same as #640

**Comment by ICA3DaR5** [comment] 2018-06-08 17:36
I have stated three weeks ago that this is a duplicate of #640, you haven't responded on either of the issues. The translation guides are going to slash all the voters of this issue.

**Closed by ICA3DaR5** 2018-06-08 17:36 UTC
Labels: Translation
