### ISSUE TITLE
O>Implement w3c verifiable claims api on RChain and their usecases worked out.

### ISSUE THREAD

**Issue by Viraculous** [rchain/bounties#334] opened 2018-02-12 17:40 UTC
>  @Viraculous Feedback from Bas Kapijn ( Architect of ICTU/Discipl ); Hello Victor, note we are a very small team. There hasnt formed yet a real community around discipl. We (some of our team) might think of using rchain in some future project and as such might collaborate with the rchain community but i cant say for sure nor when. We are not really talking about it and are busy with a lot of other things to be honest. I'd be helped more when apart from such a project the rchain community would try and help build a discipl core binding to rchain instead of the other way around (us building it ourselves in the rchain community of which i don't think will happen given our ample time/resources). In a sense this would mean collaboration too as i'd have to explain rchain devs more about what discipl actually is and make discipl core more mature. Note that discipl core is mostly a w3c verifiable claims api on top of which a new needs centered discipl pattern api will be build. Implementing the binding to rchain would mean rchain could be a choice of platform (one of the supported platforms) for use cases (8 of them currently in development) build upon discipl core. If rchain dev people are interested in this, they can contact me (note also: then it would be best when these people are living in nl so we could meet once or twice). I hope this helps?. Regards  Bas Kapijn.  #247 

https://www.w3.org/2017/vc/WG/
https://www.w3.org/TR/verifiable-claims-data-model/

- [ ] Implement w3c verifiable claims api on RChain

- [ ] Get their 8 use cases.

 

Measure of Completion:  Implemented w3c verifiable claims on api on RChain and working use cases.
Suggested Budget:$3000
Time: Before end of March

**Comment by David405** [comment] 2018-02-14 10:54
@Viraculous, I sent a mail to w3c but they are yet to reply, I have been doing a lot of studies concerning this and would give the group a reply later today or tomorrow, do you have any progress report yet?

**Comment by dckc** [comment] 2018-02-14 14:58
@Viraculous I think it will be more than two weeks until the rholang compiler and such support even the most basic contracts. And even then, two weeks to implementing the API and work out the use cases doesn't seem realistic. Are you offering to get the job done in two weeks? Or estimating that someone else could do it in two weeks?

**Comment by Viraculous** [comment] 2018-02-14 16:31
@David405 , thank you for your for efforts. I would like to get your reply from the w3c. I will keep in touch with Bas kapijn and w3c with as much as possible. @dckc as for the time, its not objective, its an estimate. It can be adjusted to a more flexible time space. How about before the end of march? It must be noted however that this issue is a crop out of the mother issue #247 . Drawing from Bas Kapijn's reply, our developers can reach out in collaboration with Bas Kapijn.

**Comment by dckc** [comment] 2018-02-14 23:10
"our developers"? Who does that refer to?

**Comment by Viraculous** [comment] 2018-02-15 00:14
@dckc did you fully read the quote? Its an inference from Bas Kapijn it.

**Comment by dckc** [comment] 2018-02-15 03:09
I'm still struggling to understand.

So Kapijn and his development team can reach out... to whom?

And @David405 where did you send your email? I don't see anything relevant in the [wg archives](https://lists.w3.org/Archives/Public/public-vc-wg/)

**Comment by David405** [comment] 2018-02-15 11:40
@dckc, if you study the documents carefully you should find relevant information. there is a mailing list at the right side of the page. For more information on verifiable claim use cases check out https://www.w3.org/TR/verifiable-claims-use-cases/

**Comment by dckc** [comment] 2018-02-15 21:09
I have studied the documents.

What is the url of the archived copy of your mail message?

**Comment by David405** [comment] 2018-02-16 03:27
Here is the url https://lists.w3.org/Archives/Public/public-publ-wg/2018Feb/0159.html

**Comment by dckc** [comment] 2018-02-16 04:56
So you sent it to public-publ-wg@w3.org; that's a mailing list for the publishing working group.

The verifiable claims document says:
> Comments regarding this document are welcome. Please send them to public-vc-comments@w3.org 

In any case, I don't know why you would expect the verifiable claims working group to provide "an urgent robust documentation or tutorial ... on how to get Discipl Api and verifiable working claim". Your message is not a comment on the spec. It's a request for an entirely separate work product; one that is not in their scope.

If you demonstrate that you have put significant effort into integrating Discipl with verifiable claims and you are having some difficulty with a specific part of the VC spec, you could expect them to explain that part of the spec.

**Comment by David405** [comment] 2018-02-16 15:13
@dckc, I understand your point, if you have made any effort integrating Discipl with verifiable claims I would love to see what you have done, it would act as a guide of some sort.

**Comment by dckc** [comment] 2018-02-17 04:26
I have not done any work with Discipl.

I try to see that at least the **Development** issues are on track. I still don't see a realistic objective here. As indicated by the **needs-SMART-objective** label, I'm inclined to close this unless I see progress or a refined plan from one of the assignees within a few days.

**Comment by Viraculous** [comment] 2018-02-27 01:10
@dckc, am not skilled in development issues and as such have little knowledge of how SMART this issue could be. You suggested reducing the scope of the issue, would that help making it more actual?  I guess u have a better idea using w3c claims, please let's see how to get the issue SMART and actionable. Permit me to assign you.

**Comment by BelovedAquila** [comment] 2018-02-27 02:16
@dckc I think the issue is worth looking into,  if closely looked into,I think it's realistic objective would be seen, since @Viraculous isn't skilled in developments issues, I suggest @David405, @hyperevo and likewise yourself could look closely into it, the issue of #247 has gone soo far to just be abandoned on the stand of no clear objective,you could actually help to see that this development issue goes on track, we want to see that we don't lose a vital connection as that of discipl, at least not after making high paces, communication and interest.we won't be wrong believing in your development expertise on this,  don't you see it in closely same perspective?

**Comment by dckc** [comment] 2018-02-27 19:39
@msporny my energies are currently directed elsewhere, so if it were up to me, I was going to close this as **wontfix**. But maybe it's something we should talk about... let me know if you want me to fill you in on RChain and talk about how a verifyable claims implementation could fit in.

It might be fun to take a crack at it in monte (see #427).

**Comment by dckc** [comment] 2018-03-07 01:24
looks like both @msporny and I have too much on our plates to move this forward.

Anybody who does significant work on it, go ahead and reopen it.

**Closed by dckc** 2018-03-07 01:24 UTC
Labels: Development, needs-SMART-objective
