### ISSUE TITLE
Translate RChain Cooperative (Medium) Blog Posts to French

### ISSUE THREAD

**Issue by Pionelle** [rchain/bounties#640] opened 2018-04-30 00:39 UTC
**https://medium.com/rchain-cooperative**

**https://medium.com/@rchainfrench**

*More people reading the blog posts in other languages means good marketing* 

[Please make the issue SMART: Specific, Measurable, Achievable, Realistic, Timely.]

*Estimated Budget of Task:* **$[2200]**  \
*Estimated Timeline Required to Complete the Task:* **[3 days]**  \
*Measure of Completion:* **[100%]**

[See CONTRIBUTING.md for details on budget and reward process.]

--  \
***Legal***  \
*Task Submitter shall not submit Tasks that will involve RHOC being transacted in any manner that (i) jeopardizes RHOC’s status as a software access token or other relevant and applicable description of the RHOC as an “asset”—not a security— or (2) violates, in any manner, applicable U.S. Securities laws.*

### For Translators

[Thanks for your interest in telling the story of RChain in another language.]

  - Why this document?
    - It's important to translate because ____
    - [x] It's an [RChain blog](https://medium.com/rchain-cooperative) item
    - [x] It's on https://developer.rchain.coop/ that has been endorsed
          for translation by @Jake-Gillberg, @MParlikar, or @KellyAtPyrofex 
  - How can people who do not speak this language be assured of the quality of the translation? (all are required)
    - [x] several reviewers are involved (_assign the ticket to them_)
    - [ ] at least two of them have high proficiency in (the target language)
    - [ ] at least two of them have high proficiency in English
    - [ ] at least two of them have either
       - [ ] significant reputation (e.g. a diploma) at stake; source: ____
       - [ ] a track record of quality work on rchain bounties: #nn, #nn, ...
  - What about maintenance? (choose one)
    - [ ] the source document is stable; further translation work is not expected
    - [ ] our plan to keep the translation up to date is: ____

**Comment by Pionelle** [comment] 2018-04-30 00:43
https://medium.com/@rchainfrench/resonate-et-lifeid-sont-ravis-dannoncer-une-nouvelle-collaboration-9a67e49be484

Juste pour sortir quelque chose aux francophones

**Comment by jasoncruzzy** [comment] 2018-04-30 00:54
@Pionelle how do we verify the authenticity of the Documented #translation?

**Comment by truffard** [comment] 2018-04-30 09:08
@Pionelle bonjour...can you be a little more specific about the task? Quels documents doivent etre traduits? Merci

**Comment by BelovedAquila** [comment] 2018-04-30 09:33
@Pionelle, @truffard et moi les ferait la revue

**Comment by Pionelle** [comment] 2018-04-30 14:35
#633 La plupart des documents faits par lui

**Comment by Pionelle** [comment] 2018-04-30 14:39
@truffard I try to translate the non technical articles by RChain cooperative.

**Comment by truffard** [comment] 2018-04-30 15:19
@Pionelle tu veux dire les posts de ce blog?
 https://medium.com/rchain-cooperative
Si oui, il faut s'entendre sur qui traduit quels postes pour ne pas avoir de redondances.

**Comment by truffard** [comment] 2018-05-02 16:36
voila ce que j'ai traduit
https://www.youtube.com/watch?v=G4fSrC-43GE

**Comment by jasoncruzzy** [comment] 2018-05-02 22:58
Really nice work

**Comment by truffard** [comment] 2018-05-03 05:10
@lapin7 je dois contacter le propriétaire de la vidéo sur sa chaine pour cela ou existe t'il un moyen de le faire directement sur Youtube?

**Comment by ICA3DaR5** [comment] 2018-05-18 20:59
First, you have posted only two blog posts instead of the whole blog as implied and the budget seems too high for two blog posts.

**Comment by ICA3DaR5** [comment] 2018-06-08 12:59
I Google translated the original (English) blog posts to French, and it seems to me that the French translation you have posted here is Google translated.

**Comment by ICA3DaR5** [comment] 2018-06-08 18:31
Since this is a duplicate of #623 and I have stated [my opinion](https://github.com/rchain/bounties/issues/623) there, the translation guides are going to slash all the voters of this issue.

**Closed by ICA3DaR5** 2018-06-08 18:31 UTC
Labels: Translation
