### ISSUE TITLE
Need to Establish an Automated Email to Members to INCREASE Voting and Serve as Reminder to Vote on Issues

### ISSUE THREAD

**Issue by tucsonblockchain** [rchain/bounties#946] opened 2018-08-31 21:35 UTC
### Benefit to RChain
To increase voting on issues for all members, including those who worked on bounties. To bring ease of use and a better user experience while quantifying the results via an email system (from members and the provided email at signup) and to diminish outright apathy in voting process or simply to help others figure out how to vote at all. Get out and VOTE initiative.

### Budget and Objective

Estimated Budget $7,500
Estimated Timeline - 1 month
How measured? 
Currently there must be a way to quantify voting on all issues. We must arrive at these quantifiable results. The measurable objective is to increase the voting results relative to the issues and number of votes (ratio) to a much higher standard, that of sending out email reminder of all voting in process, and to quantify the results by an increase relative to number of issues and votes (ratio) of a minimum of 250% increase - a measurement compared to the current model, and if 250% is achieved, and that goal is met, then the budget is paid. Another measurement that will be gauged is the will of the members of RChain by support shown in by comments in Discord and by polling at RchainCommunity.xyz though this has no bearing in the quantifiable results and the growth goal of 250% (increase) OR NO BOUNTY IS PAID AT ALL. The results can then be compared month after month and compared to the current system. Some can't even figure out how to vote. Others never get around to voting at all, or there are very few votes, but at least people can get a reminder and an email in their inbox to vote and what issues are up for vote. I say let the results speak for themselves vs the current model and voting ratios and if no 250% increase is achieved (relative to ratios), then no bounty is paid at all.

**Comment by tucsonblockchain** [comment] 2018-08-31 21:42
ICA3DaR5 is seeking support for his build on his awesome site RchainCommunity.xyz and I fully support and would vote if I could, but I have no clue how to vote and I would imagine new members and existing members may be having issues even voting or even knowing how to vote. To this extent, it is a disservice to people working on bounties and I believe a simple Email reminder for each vote will vastly improve the vote count. Now democracy in general is a dangerous thing. But in this case I believe an email will increase the voting , and bring greater reward to RChain community as a whole vs one where many aren't even aware of the vote let alone know how to. A simple email in an member's inbox that takes them to that ballot or vote process is a step in the right direction for ease of use and a much better and improved user experience, but as it stands right now, ICA3DaR5 may not even get my vote because I have no clue how. And I bet I am not the only one.

**Comment by deannald** [comment] 2018-09-01 03:13
The Coop (and RChain Europe has the mandate on this) is currently working on developing most of this out so this work would be duplicative and possibly very confusing to members as to where to go for source of information. It would be helpful to have a short discussion with Cooperative staff as to what the intent of this Bounty is so the bountyists have a better understanding of what is in development.

@ian-bloom

**Comment by tucsonblockchain** [comment] 2018-09-01 03:46
The intent is fully disclosed.

**Comment by David405** [comment] 2018-09-01 03:47
Brent, I understand your concerns, for new members especially, the voting process might be a challenge. At Colab, @Valentine-Mario and I have successfully staged an automated bot that would guide people throughout their experience with the rewards App, you or anyone could try it out in [rewards-test](https://rewards-test.rhobot.net/) to see how it helps improves your experience with voting on issues. We would require a lot of feedback and constructive criticism to continue improving on it to provide the best possible assistance. We hope to have it merged with the main rewards app soon after Rcon3.

As regarding the reminder, I believe the engagement by label guides and the TAC (@dckc ) provides enough motivation to vote on issues that are of value to the Coop.

**Comment by tucsonblockchain** [comment] 2018-09-01 03:48
I was thinking a bot (a bot to go to) to get the same thing an email would do would suffice. In fact I was wondering if it was legit to add that to this issue!

**Comment by dckc** [comment] 2018-09-19 22:39
This is a duplicate of other coop work, as noted in https://github.com/rchain/bounties/issues/946#issuecomment-417828613

**Closed by dckc** 2018-09-19 22:39 UTC
Labels: Voting, duplicate, zz-Operations
