### ISSUE TITLE
Video animation that explains RChain's collaboration and bounty app.

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#559] opened 2018-03-28 13:14 UTC
# Create a video animation that explains RChain's collaboration and bounty app.

**To get a smooth collaboration, that allows for 10,000 collaborators to work on.**  

## Measure of completion
- [x] contacted marketing
- [x] video script / story line
- [x] target groups defined
- [ ] summary to go on youtub
- [ ] key words
- [ ] link on central website
- [ ] link in newsletter

## Onboarding
- [ ] join [RChain](https://member.rchain.coop/#/sign-in)
- [ ] join github, get invitation for [repository Bounties](https://github.com/rchain/bounties/)
- [ ] join [rchain@googlegroups.com](https://groups.google.com/forum/#!forum/rchain/join)
- [ ] send your discord name, github name and real name to ops@rchain.coop.
- [ ] [read](https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App) about our [Decentralized Bounty App RChain](https://rewards.rchain.coop/)

## Work
- [ ] create an issue
- [ ] get collaborators

## Bounty
- [x] become verified member in DBAR
- [x] add a budget to issue
- [x] add a reward to worker on issue
- [x] get confirmation from collaborator for budget and reward
- [x] create an invoice
- [x] send invoice to Finance
- [ ] receive payment
- [ ] upgrade your voting rate
- [ ] suggestions to convert RHOC into BTC 

## Related stuff
 - [rchain/bounties/CONTRIBUTING.md](https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md)
 - [How To Use the Budget Rewards Web App](https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App) wiki page
     - [RChain web app tutorial video](https://drive.google.com/file/d/12aOF6uV3lEnYBFtqV9KHllw-Xi-BB1Ux/view) from #536 
 - [trust network visualization](https://rewards.rchain.coop/trust_net_viz.html)
https://github.com/rchain/bounties/issues/260#issuecomment-362630020
https://github.com/rchain/bounties/blob/master/README.md
 - #491 For user experiences

## Suggested Budget
$2000

## Duration
2 weeks

## Maintenance
- [ ] What about maintenance?

**Comment by Cryptovideos** [comment] 2018-03-28 13:21
Guys regards the script - any available piece on RChain's collaboration and bounty app

**Comment by lapin7** [comment] 2018-03-28 13:25
https://github.com/rchain/bounties/blob/master/CONTRIBUTING.md

**Comment by lapin7** [comment] 2018-03-28 13:26
https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App

**Comment by ResonanceXX** [comment] 2018-03-28 13:26
From what angles are you Considering? Is this like a visual element to the information already on the ground. Or are we towing the line of  some impressive videos where "a hand scribbles information down"Or do we have to innovate some new ideas as to how we can create an animation incorporating a certain theme. ( Like the multiplicity and diversity in the Coop) 
Good to work on this one. 

Sent from Yahoo Mail on Android 
 
  On Wed, 28 Mar 2018 at 14:21, Cryptovideos<notifications@github.com> wrote:   
Guys regards the script - any available piece on RChain's collaboration and bounty app

**Comment by lapin7** [comment] 2018-03-28 13:37
@ResonanceXX Please add all links to _"information already on the ground"_ to the description of this issue under **Related Stuff**

**Comment by Cryptovideos** [comment] 2018-03-28 14:03
Tks for the Links @lapin7 ill devise a script and upload it for approaval

**Comment by Cryptovideos** [comment] 2018-03-28 14:07
@ResonanceXX ill be creating a full-on animated video based off the script, visually engaging and very creative. when you spak of "a hand scribbles information down" you are actually meaning Whiteboard animation explainers wich i do as well however this is going to be way better than that! Watch this space.....hopefully a great start to many fantastic marketing projects from me..

**Comment by Cryptovideos** [comment] 2018-03-29 06:25
@lapin7 heres my take from the various info 

RChain’s Distributed Budgeting and Rewards Bounty Program consists of a programe whereby funds are allocated to a reward system for working together on various issues.
In order to qualify for rewards, Membership in the RChain Cooperative is required for later parts of the process, but to create an issue, all you need is simply create a GitHub account so that you can create or collaborate on work items represented by various rchain/bounties github issues.
The process works via a decentralized Budget Allocation system whereby Voting and collecting of rewards requires a verified membership within in the RChain Coop.

Budgets are allocated to work items by at least three Members thereafter, the average of three votes from the three verified members defines the budget allocation to the issue.

During the month each member may vote on what portion of the budget is distributed to each collaborator as a reward for their participation. The average of (at least three) votes sets the personal reward for each collaborator. and the RHOC are distributed monthly based on invoices submitted.

By joining the Cooperative you will be able to participate in the lively conversation of the RChain community, vote on budgets and rewards, and submit your invoices

**Comment by kitblake** [comment] 2018-03-29 06:59
Sounds good. Is this a script for a voice-over? If so I will make some minor edits. But if it's purely a description then it's on target.

**Comment by lapin7** [comment] 2018-03-29 07:19
@Cryptovideos that's awesome! You've understood it perfectly.

The video script could start with a general attractive explanation and then dive deep into a tutorial about how to do that all. It's best to edit/change/add this file:
https://github.com/rchain/bounties/wiki/How-To-Use-the-Budget-Rewards-Web-App

Then in the video recorded screen sessions about the subjects in the first issue description above could make it clear.

Please tell me what you think.

**Comment by Cryptovideos** [comment] 2018-03-29 07:45
@kitblake  it is in fact a Voice Over Script sir - please tweak it and re-upload here?

@lapin7 A tutorial video is already done i see and the information around it clear and comprehensive- i can do it better by sprucing it up and adding effects and such as well as a professional voice over, **HOWEVER** this must not be included into the Animated Explainer. 

We need to keep the Current Video tight and precise and under 2 minutes as per industry standards, to the point and in accordance to the script and not deviate this ,also i am working as per the budget assigned to this animated project.

i would advise any tutorial videos and application / system walk through videos / Processes and procedures instructional videos, be produce in a more corporate and clean manner as i do for other industry. This i wold chat to you about seperately on completeion of the current Animated Expaliner Video

i hope i make sense??

**Comment by lapin7** [comment] 2018-03-29 08:03
@Cryptovideos 
That makes a lot of sense. Please create new issues that more or less de-compose this issue #559 and while doing that, edit this issue to make it more concise.
It would be great if the existing tutorial video is spruced up :-) and de-composed into short clips of less then 2 minutes.
Please set up a draft for getting a more corporate and clean manner.
Maybe a standard intro with a tune or so. Anyway you know best how to do such things. ;-)

**Comment by Cryptovideos** [comment] 2018-03-29 08:11
Ok cool @lapin7   - Thanks for understanding! This is my Game and im good at it! 

Please could i ask you a favor - i need a High-Res Image of our Logo/Artwork ( the Rchain logo)  - i want to create an animated  / special effects intro - we will then make sure that all corporate tutorial video's and such have a uniform and Standrad intro and outro  for all these videos - to keep consistency across the the brand.

Regards the other issues - i will definitely move on to those once we have this Animated explainer done and completed. 

i agree we should segment that current tutorial video into shorted sections, add music and special effects including the new Logo animation intro and outro. It will make a massive differance.

**Comment by lapin7** [comment] 2018-03-29 08:35
High-Res images
https://github.com/rchain/style_guide_and_files/tree/master/print

**Comment by lapin7** [comment] 2018-03-29 09:32
This [High Level Marketing Plan](https://docs.google.com/document/d/1tfoZMB7tedcsqZG6enGsCN4qR6l6AZSCUNrdMUs_0c4/edit) may also be of interest

It's discussed in https://github.com/rchain/bounties/issues/550

**Comment by Ojimadu** [comment] 2018-03-29 22:14
Welcome onboard @Cryptovideos. For the voice over script you created, I would you create a google doc and share it with rchain@googlegroups.com so that collaborators on this repository can suggest/ improve on the document. If you any troubles doing that I can help you out.
Would like to see an explainer video on 
- how to contribute to the bounty program
- how to use the budget app (might be delayed because the app still have some issues)
- explainers on key concepts of rchain like namespaces, concurrency, CBC casper etc.
Great to have you on board. Welcome on here once again.

**Comment by ResonanceXX** [comment] 2018-03-30 01:55
@lapin7 The RChain Marketing Plan is a beautiful piece of information. And the volume of it also is unique.
@Cryptovideos  You should consider working your way to the **Number 4 -  Goals** Category. There- lies a concise outline of RChain's achievable goals, listed.
Your reputation should precede you nicely, and if need be I suggest an even more artistic conveyance of such information to the general public.
 So that we maybe 
![screenshot-2018-3-30 rchain maketing plan draft - 1](https://user-images.githubusercontent.com/34219332/38121214-d0e83682-33c5-11e8-97bc-e7cc1e09f950.png)
pull off an ''all you can get in one shop'' move on both potential Co-op members and Blockchain start ups hungry for information about us.

- Cheers!

**Comment by Cryptovideos** [comment] 2018-03-30 06:00
@Ojimadu  Lovely to "Meet" you brother and thank you kindly for the Linkedin Connection invite - i have accpeted by the way! :)

Regards the google Doc script - i willl do that but please note that we are already almost done with it - barring a few minor tweaks as per @kitblake suggestions. At the same time i need to get cracking on this as iv already started planning the scenery for each section of the storeyboard, and there needs to be execution now

**Comment by Cryptovideos** [comment] 2018-03-30 06:26
@Ojimadu - the email has been sent as per your suggestion -ill need to get cracking on this project soon tho so we don't want to delay too much considering we are pretty close to a fantastic easy to understand script already. Please look at it yourself and push the guys any way you can to get this thing finalized. 👍 💯 🥇 and lets aim to close the script issue by tomorrow evening.

Now for you other suggestions " Would like to see an explainer video on 
- how to contribute to the bounty program
- how to use the budget app (might be delayed because the app still have some issues)
- explainers on key concepts of rchain like namespaces, concurrency, CBC casper etc.
Great to have you on oard. Welcome on here once again."

The Above suggestions you make are really great and i feel would do well to explain and showcase Rchain aspects nicely. I can do them once we assign budget on it and get approval etc - these would fall into place on completion of the current project tho.

For now lets get energized and get the ball rolling and be Pro-Active!! 

May i humbly ask you to forward relevant info i can extract on the following topics to start planning the process on the following? 

1)  How to contribute to the bounty program
2) How to use the budget app
3) Concepts of rchain like namespaces, concurrency, CBC casper etc

Tks @Ojimadu for the warm welcome and im really excited to be a part of this amazing team

**Comment by Ojimadu** [comment] 2018-03-31 18:29
@Cryptovideos I cant find any draft to look at but you can proceed with the progress made with kitblake instead of waiting for me. We can work another some other information requested above.

**Comment by kitblake** [comment] 2018-04-01 05:07
@Cryptovideos Here's an edit of the voiceover. I made it shorter and more streamlined, but you should adjust as needed. 

RChain’s Distributed Budget & Rewards Bounty Program consists of an application where funds are allocated to budgets for collaborating on Github issues.

In order to qualify for rewards, Membership in the RChain Cooperative is required. But to create an issue, all you need is a GitHub account so that you can post and collaborate on work items represented in Github rchain/bounties. The bounty process works via a communal budget & reward allocation system with peer review and voting.

Budgets are allocated to work items by at least three Members. The average of the votes from three or more Members defines the budget for the issue.

During the month each member may vote on what portion of the budget is distributed to each collaborator as a reward for their participation. The average of (at least) three votes sets the personal reward for each collaborator. RHOCs are distributed monthly based on invoices submitted.

By joining the Cooperative you'll be able to participate in the lively conversation of the RChain community, vote on budgets and rewards, and earn RHOCs for bounties.

**Comment by Cryptovideos** [comment] 2018-04-01 08:55
@kitblake this is fantastic! Thank you for this!!

**Comment by Cryptovideos** [comment] 2018-04-01 10:09
Guys can you vote this project please - still tying to figure out all these procedures and steps....??

**Comment by Cryptovideos** [comment] 2018-04-01 10:17
![screen shot 2018-04-01 at 12 15 25](https://user-images.githubusercontent.com/37866851/38172109-7a3a7556-35a6-11e8-8968-e9539b3372e8.png)
Guys please proceed to vote - ill then get cracking

**Comment by kitblake** [comment] 2018-04-01 12:58
@Cryptovideos You should vote too. (Login first and) in the lower frame click the the New BudgetVote button:
https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=559#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-action%3Drelated_records_list%26num%3D%253D559%26-relationship%3DBudgetVotes%26-table%3Dissue%26-ui-root%3Dmain-content%26--msg%3DRecord%2Bsuccessfully%2Badded%2Bto%2B%2522BudgetVotes%2522%2Brelationship.

**Comment by Cryptovideos** [comment] 2018-04-01 13:07
I’m battling for verification  for my account and then was reimbursed 20$

On 01 Apr 2018, at 14:58, kitblake <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> You should vote too. (Login first and) in the lower frame click the the New BudgetVote button:
https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=559#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-action%3Drelated_records_list%26num%3D%253D559%26-relationship%3DBudgetVotes%26-table%3Dissue%26-ui-root%3Dmain-content%26--msg%3DRecord%2Bsuccessfully%2Badded%2Bto%2B%2522BudgetVotes%2522%2Brelationship<https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=559#&detail-url=https://rewards.rchain.coop/index.php?-action=related_records_list&num=%3D559&-relationship=BudgetVotes&-table=issue&-ui-root=main-content&--msg=Record+successfully+added+to+%22BudgetVotes%22+relationship>.

**Comment by Cryptovideos** [comment] 2018-04-01 13:09
Ok iv managed to get this far :
[cid:25E26DD5-1E10-494E-AC3A-EB47E6E4A02B]
On 01 Apr 2018, at 14:58, kitblake <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> You should vote too. (Login first and) in the lower frame click the the New BudgetVote button:
https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=559#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-action%3Drelated_records_list%26num%3D%253D559%26-relationship%3DBudgetVotes%26-table%3Dissue%26-ui-root%3Dmain-content%26--msg%3DRecord%2Bsuccessfully%2Badded%2Bto%2B%2522BudgetVotes%2522%2Brelationship.

**Comment by Cryptovideos** [comment] 2018-04-01 13:11
Id made a start last night but have halted since my accounts needs to go through all the verification processes as well as i need to sublet a w8 Tax form that my Tax consultant here in South Africa is trying to figure out - iv been left frustrated and will do what i can to get all of these steps done

On 01 Apr 2018, at 14:58, kitblake <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> You should vote too. (Login first and) in the lower frame click the the New BudgetVote button:
https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=559#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-action%3Drelated_records_list%26num%3D%253D559%26-relationship%3DBudgetVotes%26-table%3Dissue%26-ui-root%3Dmain-content%26--msg%3DRecord%2Bsuccessfully%2Badded%2Bto%2B%2522BudgetVotes%2522%2Brelationship.

**Comment by Cryptovideos** [comment] 2018-04-01 13:14
[cid:FA49E6EE-52C4-4EBE-9ACA-E2275D38876A][cid:EE500937-FBE6-467B-8777-D442D30AC914]P[cid:FF60EF94-1BF5-49E7-83D4-700B20EE286D]roject Progress Snapshots


[cid:1C60188B-23DD-4F32-83B3-0FD7A256E6AB]
On 01 Apr 2018, at 14:58, kitblake <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> You should vote too. (Login first and) in the lower frame click the the New BudgetVote button:
https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=559#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-action%3Drelated_records_list%26num%3D%253D559%26-relationship%3DBudgetVotes%26-table%3Dissue%26-ui-root%3Dmain-content%26--msg%3DRecord%2Bsuccessfully%2Badded%2Bto%2B%2522BudgetVotes%2522%2Brelationship.

**Comment by Cryptovideos** [comment] 2018-04-01 13:27
again cant seem to verify my account i get this error message “:
[cid:A9BE5494-090C-4EE9-BE22-D95A07BDAECF]


On 01 Apr 2018, at 14:58, kitblake <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> You should vote too. (Login first and) in the lower frame click the the New BudgetVote button:
https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=559#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-action%3Drelated_records_list%26num%3D%253D559%26-relationship%3DBudgetVotes%26-table%3Dissue%26-ui-root%3Dmain-content%26--msg%3DRecord%2Bsuccessfully%2Badded%2Bto%2B%2522BudgetVotes%2522%2Brelationship.

**Comment by Cryptovideos** [comment] 2018-04-01 13:41
![screen shot 2018-04-01 at 15 11 20](https://user-images.githubusercontent.com/37866851/38173686-1d50a5dc-35c3-11e8-8bb6-657281b4aeb6.png)
![Uploading Screen Shot 2018-04-01 at 15.11.26.png…]()
![Uploading Screen Shot 2018-04-01 at 15.11.43.png…]()
![Uploading Screen Shot 2018-04-01 at 15.11.52.png…]()

**Comment by Cryptovideos** [comment] 2018-04-01 14:11
ok  - iv joined the Chain Discord group but who i try verify my account via the Rchain app i get this error message : Your discord user is not in the coop member role in the RChain discord guild.

On 01 Apr 2018, at 14:58, kitblake <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> You should vote too. (Login first and) in the lower frame click the the New BudgetVote button:
https://rewards.rchain.coop/index.php?-table=issue&-limit=30&num=559#&detail-url=https%3A%2F%2Frewards.rchain.coop%2Findex.php%3F-action%3Drelated_records_list%26num%3D%253D559%26-relationship%3DBudgetVotes%26-table%3Dissue%26-ui-root%3Dmain-content%26--msg%3DRecord%2Bsuccessfully%2Badded%2Bto%2B%2522BudgetVotes%2522%2Brelationship.

**Comment by Cryptovideos** [comment] 2018-04-01 19:12
Hey Ojimadu

Thank you for taking the time to enlighten me - i really appreciate this

On 01 Apr 2018, at 19:22, Ojimadu <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> PM @makys<https://github.com/makys> or @ian<https://github.com/ian> on the discord channel for verification. After that you can verify your membership on the rewards app so your votes can count.

**Comment by Cryptovideos** [comment] 2018-04-04 05:43
Happy to announce the Makays has confirmed my account verification! awesome stuff

**Comment by Cryptovideos** [comment] 2018-04-04 07:02
Stimulation!! Hahaha LOVE IT

Don’t worry team - this video is looking reeeallllyyy good already - so excited to present it soon!!

On 04 Apr 2018, at 08:22, HJ Hilbolling <notifications@github.com<mailto:notifications@github.com>> wrote:


As soon as the Bounty App<https://rewards.rchain.coop/> has picked up that @Cryptovideos<https://github.com/Cryptovideos> is a verified member, the Invoice 201803-Cryptovideos<https://docs.google.com/spreadsheets/d/1EZnV6548YZLg87o1Z4g6Pz65K4ij_u1PgnhuQtpSZ44/edit#gid=910870020&range=B1:H1> will show the correct reward for issue #559<https://github.com/rchain/bounties/issues/559>.
And @Cryptovideos<https://github.com/Cryptovideos> can download the invoice as PDF and send it to ops@rchain.coop<mailto:ops@rchain.coop> for verification. After that he can send the PDF to invoices@rchain.coop<mailto:invoices@rchain.coop> and ASAP he will get paid in RHOC at the rate of the payment day.

This arrangement should stimulate @Cryptovideos<https://github.com/Cryptovideos> to make an awesome video animation :-)

**Comment by Cryptovideos** [comment] 2018-04-04 18:48
Hi Team

Just doing some minor tweaks and final touches - a video link will come through within the next hr or so

On 01 Apr 2018, at 19:22, Ojimadu <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> PM @makys<https://github.com/makys> or @ian<https://github.com/ian> on the discord channel for verification. After that you can verify your membership on the rewards app so your votes can count.

**Comment by Cryptovideos** [comment] 2018-04-04 19:45
Here We go guys : https://youtu.be/vcIZSZmpO9E

**Comment by Cryptovideos** [comment] 2018-04-05 07:18
@lapin7 @kitblake please update me?

**Comment by lapin7** [comment] 2018-04-05 11:12
@Cryptovideos awesome video animation. Very well explained.
Let's put a small summary under the Youtube video with links to the needed places.

**Comment by Cryptovideos** [comment] 2018-04-05 11:41
Hi guys - can we upload this to the official Rchain Youtube channel?

I highly suggest you do that instread - then add the links and correct descriptions??

Im happy to upload it there if you can give me access to the Youtube channel?

On 05 Apr 2018, at 13:12, HJ Hilbolling <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> awesome video animation. Very well explained.
Let's put a small summary under the Youtube video with links to the needed places.

**Comment by kitblake** [comment] 2018-04-05 13:43
Wonderful work @Cryptovideos! (duping my Discord comment here). 

@patrick727 Can we add this to the YouTube channel?

**Comment by Cryptovideos** [comment] 2018-04-05 14:50
Thanks so much!!

**Comment by makys** [comment] 2018-04-05 14:58
Thanks @Cryptovideos . Succinctly Executed! I like it.

**Comment by Cryptovideos** [comment] 2018-04-05 15:55
AWESOME tsk for the amazing feedback! Im
really pumped up about Rchain!!

On 05 Apr 2018, at 16:58, makys <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @Cryptovideos<https://github.com/Cryptovideos> . Succinctly Executed! I like it.

**Comment by dckc** [comment] 2018-04-13 02:44
#598 is my proposal for adding links from README and CONTRIBUTING. I used a badge because embed doesn't seem to work. Please take a look.

**Comment by kaka56** [comment] 2018-04-13 16:16
@Cryptovideos  this is good work .Sharing this video will go a long way onboarding  coop members.

**Comment by Cryptovideos** [comment] 2018-04-14 19:39
@kaka56 appreciate the props - tks for the feedback

**Comment by raven104** [comment] 2018-04-14 23:44
@crytovideos that is a really welcome idea, I look forward to a video that really reflects the RChain brand in terms of vibrancy.
One thing I'd like to see is good colour theme. The current video seem flat, if you can improve on the animation that will be awesome.
Are you looking to use the same storyline or revamp that altogether.

**Comment by Cryptovideos** [comment] 2018-04-15 07:00
Hey raven104, great questions!!

Ill be revamping the animation altogether with brand new scenery, motion graphics and a completely vibrant colour themed project that better reflects the Coop.

Ill redo the voice over and backing music track as well, i feel its all mundane, flat and obsolete.

Ill only make use of the wording from the existing “script” it does well to explain the coop at least, but ill look at that a bit closely as well, as i may tweak it slightly.

ill get onto this as soon as possible

tsk for the positivity



On 15 Apr 2018, at 01:44, raven104 <notifications@github.com<mailto:notifications@github.com>> wrote:


@crytovideos that is a really welcome idea, I look forward to a video that really reflects the RChain brand in terms of vibrancy.
One thing I'd like to see is good colour theme. The current video seem flat, if you can improve on the animation that will be awesome.
Are you looking to use the same storyline or revamp that altogether.

**Comment by Pionelle** [comment] 2018-04-15 07:15
This is a good video
The animations are lovely
There is a problem with the subtitle text which is different, and confuses RChain for Ourchain sometimes. There are other text mistakes.
But it takes nothing away from the video being important.
If these can be corrected for fair English language speakers.

**Comment by TrenchFloat** [comment] 2018-05-08 16:07
I see "summary to go on youtube, key words, link on central website, link in newsletter" as not yet done in the initial comment. @Cryptovideos, could you add a description with links to mentioned places and some tags to your video? @PatrickM727 can we put https://youtu.be/vcIZSZmpO9E in the newsletter and the RChain YouTube channel?

**Comment by Cryptovideos** [comment] 2018-05-08 17:01
Hey there Kyle

Tsk for reaching out

So i highly recommend this goes onto the Rchain channel…. if something were to happen to me and my channel got removed “God Forbid” the work would be lost - its best to be on Rchains channel - what do you think guys?


On 08 May 2018, at 18:07, Kyle Connolly <notifications@github.com<mailto:notifications@github.com>> wrote:


I see "summary to go on youtube, key words, link on central website, link in newsletter" as not yet done in the initial comment. @Cryptovideos<https://github.com/Cryptovideos>, could you add a description with links to mentioned places and some tags to your video? @PatrickM727<https://github.com/PatrickM727> can we put https://youtu.be/vcIZSZmpO9E in the newsletter and the RChain YouTube channel?

**Comment by TrenchFloat** [comment] 2018-05-28 15:05
@Cryptovideos I just reached out to Patrick about putting the video on RChain's channel. Where are you on the description and tags on your video?

**Comment by Cryptovideos** [comment] 2018-05-28 16:27
Hey there Kyle

I won’t add Tags etc until i know whats happening?

Are you saying that the video is not going the loaded to the Youtube channel of Rchain? and that i must go ahead and add Tags and Descriptions?

Please clarify for me

tsk Kyle



On 28 May 2018, at 17:05, Kyle Connolly <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> I just reached out to Patrick about putting the video on RChain's channel. Where are you on the description and tags on your video?

**Comment by TrenchFloat** [comment] 2018-06-08 16:42
@Cryptovideos I misunderstood; I thought you could add tags and a description, and when we moved it to the RChain channel, everything would copy over. I realize now that's not the case, although it would only be a matter of some quick copy-pasting... Anyways.

I've reached out to Patrick who evidently looked at this issue and hasn't shown any sign of wanting to make the switch to the RChain channel. On top of that, there are links to your video on your channel everywhere (or at least there's one in the [README](https://github.com/rchain/bounties)), so I'd say it's best to leave the video on your channel.

So yes, unless there is still strong movement towards putting the video on the RChain channel, add tags and a description.

**Comment by Cryptovideos** [comment] 2018-06-08 17:08
100Percent

all good, any suggested preferences for the tags and description ?

happy to do it


On 08 Jun 2018, at 18:42, Kyle Connolly <notifications@github.com<mailto:notifications@github.com>> wrote:


@Cryptovideos<https://github.com/Cryptovideos> I misunderstood; I thought you could add tags and a description, and when we moved it to the RChain channel, everything would copy over. I realize now that's not the case, although it would only be a matter of some quick copy-pasting... Anyways.

I've reached out to Patrick who evidently looked at this issue and hasn't shown any sign of wanting to make the switch to the RChain channel. On top of that, there are links to your video on your channel everywhere (or at least there's one in the README<https://github.com/rchain/bounties>), so I'd say it's best to leave the video on your channel.

So yes, unless there is still strong movement towards putting the video on the RChain channel, add tags and a description.

**Comment by AyAyRon-P** [comment] 2018-06-27 15:30
Hey @Cryptovideos 

This is a great looking animation, is there anything else we need to add to this project or are we ready to close this out?

**Comment by Cryptovideos** [comment] 2018-06-27 16:32
This is complete to be closed but will chat to Patrick beforehand thank you for kinds words and positivity

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Closed** 2018-07-25 16:30 UTC
Labels: Education, Greeter, Marketing, Operations
