### ISSUE TITLE
review of core dev team's Rholang Tutorial

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#169] opened 2017-11-13 18:11 UTC
Alex of Coinfund is working on this.

**Comment by lapin7** [comment] 2017-11-13 21:44
We need probably a Graphical User Interface (GUI) contract constructor, containing templates of contracts and typical actions. The GUI will provide ability to create smart contracts without special technical skills.

**Comment by dckc** [comment] 2017-11-21 02:12
@alex-coinfund care to share a pointer to your work in progress?

**Comment by patrick727** [comment] 2017-11-21 15:54
yes please, 

this is something that @Jake-Gillberg would also like to help out with

**Comment by alex-coinfund** [comment] 2017-11-21 16:14
Well, I am not working on a tutorial per se, just a series of articles. Will work on the next one shortly, it will focus on the Cell contract.

**Comment by dckc** [comment] 2017-11-23 16:54
So is this a duplicate of #51?

**Comment by lapin7** [comment] 2017-11-23 17:03
@dckc I close #169 and leave #51 open.

**Comment by 9rb** [comment] 2018-01-10 18:12
what happened to the Udemy Rholang course idea?  Is that a separate topic?

**Comment by dckc** [comment] 2018-01-19 03:42
I did some relevant work by reviewing Mike Stay's...

 - [Add Rholang-Mercury tutorial doc](https://github.com/rchain/rchain/pull/159)

**Comment by Keaycee** [comment] 2018-01-25 03:11
This is an introduction and a tutorial to [smart contract language Rholang](https://www.youtube.com/watch?v=7tW1fAWg6s8).

**Comment by dckc** [comment] 2018-01-30 06:19
@AbnerZheng @tgrospic I would appreciate your input on the budget / reward for this issue.

See https://github.com/rchain/Members/issues/169#issuecomment-358858461

**Comment by tgrospic** [comment] 2018-01-31 14:05
I'm looking forward to read Mike's tutorial.

**Comment by dckc** [comment] 2018-02-21 07:17
I edited the scope w.r.t. what actually happened here.

**Closed by dckc** 2018-02-21 07:17 UTC
Labels: Development
