### ISSUE TITLE
Create a list of blockchain events for RChain

### ISSUE THREAD

**Issue by lapin7** [rchain/bounties#583] opened 2018-04-06 12:10 UTC
# Blockchain events

RChain should attend to a number of blockchain events in Africa, USA, China, Asia, Europe, Russia, .....
- [x] create a Gsheet with columns about event:
    - Name
    - Date
    - Location
    - Description
    - Target attendents
    - Number of attendents
    - Speakers
    - Importance
    - Fees
    - Reference links
    - RChain speaker
- [ ] create related SMART sub issues
- [ ] Suggested budget $1000
- [ ] Duration: 2 weeks

**Comment by Preshcode** [comment] 2018-04-06 17:56
I and @Valentine-Mario worked on creating a Google sheet with the said column <a href="https://docs.google.com/spreadsheets/d/1KnMxA1446XydwrKlOzE4DNsI38U7jJx3lrniT_yhj2c/edit?usp=drivesdk&ouid=115519494716732679966">here</a>

**Comment by Preshcode** [comment] 2018-04-06 18:03
Please elaborate on what you mean by sub issues

**Comment by jplepel** [comment] 2018-04-06 22:06
This website has a long list of events worldwide. 

https://blog.bizzabo.com/blockchain-events

**Comment by kaka56** [comment] 2018-04-06 22:08
@Preshcode @Tonyprisca13  is good we work together on this check this out [here](https://docs.google.com/spreadsheets/d/1Z7lhpf9h-9GFcILs-FvP9CtHvFPIfA2M2znFDHUT9iQ/edit?usp=drivesdk&ouid=117345271212327655578)

**Comment by jplepel** [comment] 2018-04-06 22:10
@kaka56 The doc needs permission to view. The blog post will be a good reference to see what events are out there.

**Comment by Preshcode** [comment] 2018-04-06 22:16
Yes I agree @kaka56.

**Comment by Tonyprisca13** [comment] 2018-04-07 02:44
@Preshcode @kaka56 @Valentine-Mario i am on this issue

**Comment by kaka56** [comment] 2018-04-07 06:44
@Tonyprisca13  can you paste a link so we can see how we can collaborate.

**Comment by David405** [comment] 2018-04-07 07:54
@lapin7 I cant see Africa on your list, does RChain marketing have no plan for on boarding Africans? 

Africa has a very large population with a lot of people having great interest in the cryptomarket, in Nigeria, the number of people showing excitement and accepting crytocurrencies is increasing exponentially.

**Comment by ResonanceXX** [comment] 2018-04-07 08:01
Davide405 I am very certain @Lapin7 has not intentionally left Africa out. 
The list ends with a continuation mark.....  Allowing for more entries. Your point on the viability of Africa as a fertile soil is very correct. Cheers. 

Sent from Yahoo Mail on Android 
 
  On Sat, 7 Apr 2018 at 8:54, David405<notifications@github.com> wrote:   
@lapin7 I cant see Africa on your list, does RChain marketing have no plan for on boarding Africans?

Africa has a very large population with a lot of people having great interest in the cryptomarket, in Nigeria, the number of people showing excitement and accepting crytocurrencies is increasing exponentially.

**Comment by Tonyprisca13** [comment] 2018-04-07 10:28
@Preshcode @kaka [here](https://docs.google.com/spreadsheets/d/1_Yx5vorqwGhZrz199cq9oNOLhgGNnAkjgbmxIXRxMsM/edit#gid=0) is the link to the gsheet

**Comment by Ojimadu** [comment] 2018-04-07 10:31
@Tonyprisca13 your document needs access permission.

**Comment by Tonyprisca13** [comment] 2018-04-07 11:50
I have granted access

**Comment by kaka56** [comment] 2018-04-07 12:35
@Tonyprisca13 The  document is good to go so I suggest we work together on the sheet.

**Comment by Valentine-Mario** [comment] 2018-04-07 14:28
Nice work @Tonyprisca13 I would also love to work together to improve the Gsheet

**Comment by Ojimadu** [comment] 2018-04-07 14:37
@lapin7 Is the RChain speaker supposed to be filled by the participants of this issue? As that would depend on the schedule and availability of the Speaker.

**Comment by Valentine-Mario** [comment] 2018-04-07 15:05
I added some extra events to @Tonyprisca13 spreadsheet at <a href="https://docs.google.com/spreadsheets/d/1_Yx5vorqwGhZrz199cq9oNOLhgGNnAkjgbmxIXRxMsM/edit#gid=0">here</a> . Check it out.

**Comment by Valentine-Mario** [comment] 2018-04-07 15:07
I'm pretty sure someone can add some Blockchain events in Africa.

**Comment by Viraculous** [comment] 2018-04-07 18:03
@Ojimadu , I guess the speaker should be on the decision of members of the board and that on time so that speakers could fix themselves as it is convenient.

**Comment by Tonyprisca13** [comment] 2018-04-07 18:47
@Valentine Mario please don't add up all event you come across. Not sure RChain can attend all the event it has to based on it's important.

**Comment by Preshcode** [comment] 2018-04-07 18:54
@tonyprisca13 we can't be too sure what the "important" events are. I also added some extra events.

**Comment by kaka56** [comment] 2018-04-07 20:28
@Valentine-Mario  you  messed up the sheet .

**Comment by Viraculous** [comment] 2018-04-07 22:48
@Tonyprisca13, I didn't see the column for the importance of this event to the community. Moreover I requested access to the spreadsheet.

**Comment by lapin7** [comment] 2018-04-08 08:31
> @lapin7 I cant see Africa on your list, does RChain marketing have no plan for on boarding Africans?
@David405 next time just edit the first comment and add Africa, instead of complaining that Africa is not mentioned. I did it now ;-)

**Comment by lapin7** [comment] 2018-04-08 08:38
@Tonyprisca13 please move the spreadsheet [List of blockchain events for RChain](https://docs.google.com/spreadsheets/d/1_Yx5vorqwGhZrz199cq9oNOLhgGNnAkjgbmxIXRxMsM/edit#gid=0) to [Gdrive Rchain/Members/Marketing-Community Dev/Events](https://drive.google.com/drive/folders/1FwYhwcsKLsZZVPXsgbDkRzjaHEGlROUJ)

And set Access rights to: edit for rchain@googlegroups.com

**Comment by kaka56** [comment] 2018-04-08 10:40
@Viraculous thanks for your observation the column is been added .

**Comment by kaka56** [comment] 2018-04-08 10:46
Please anyone who has editing rights on the sheet should do that carefully so as not to mess it up. I just fixed the previous one.

**Comment by jasoncruzzy** [comment] 2018-04-08 12:35
@kaka56 thanks for the work(editing)

**Comment by David405** [comment] 2018-04-09 16:07
noted @lapin7

**Comment by David405** [comment] 2018-04-10 11:24
I have added some very important blockchain events in Africa where RChain can be properly represented.

**Comment by Tonyprisca13** [comment] 2018-04-10 11:39
@David405 i see u added three blockchain africa event i will adjust them accordingly.

**Comment by dckc** [comment] 2018-04-15 13:42
I see 49 rows in the spreadsheet, but the importance column is blank. Without thoughtful consideration of which events are most important to have a presence, this is worth little more than a google search for "blockchain conference." Certainly not $1000.

**Comment by kaka56** [comment] 2018-04-15 15:26
@dckc As you can see the issue is still open which simply means there is still more research going on. Your interest should be how you can contribute to make it excellent rewards can come after.

**Comment by David405** [comment] 2018-04-16 13:36
@lapin7 I believe the first task has long been achieved.

**Comment by lapin7** [comment] 2018-04-21 06:05
@David405 what about the Importance of those events?

**Comment by lapin7** [comment] 2018-04-23 08:34
@David405 please figure changes out with @Tonyprisca13 and of course complete importance only if you know about these events

**Comment by Tonyprisca13** [comment] 2018-04-23 21:31
@David405 we can collaborate on it

**Comment by Viraculous** [comment] 2018-04-23 22:06
@Tonyprisca13, I can collaborate to get the importance of the events to the Rchain community.

**Comment by Tonyprisca13** [comment] 2018-04-23 22:41
@Viraculous Nice

**Comment by lapin7** [comment] 2018-04-23 23:15
It's a continuous job to maintain the event list :-)

**Comment by kaka56** [comment] 2018-04-24 09:14
@lapin7 you are right as some are yet to upload speakers and fees.

**Comment by David405** [comment] 2018-04-24 11:32
@Tonyprisca13 the g-sheet looks quite different from how it was formerly, I would like to be updated on the changes to the g-sheet, you can do that here or send me a pm on the discord server.

**Comment by Tonyprisca13** [comment] 2018-04-24 12:02
@David405   it's the same g-sheet

**Comment by lapin7** [comment] 2018-04-24 12:04
@David405 
If you wanna be notified:
Go to menu Tools \ Notification rules
:-)

**Comment by lapin7** [comment] 2018-04-24 12:05
Only format of the spreadsheet has changed.

**Comment by David405** [comment] 2018-04-26 14:44
@lapin7 thanks, I have added a notification rule

**Comment by PatrickM727** [comment] 2018-04-29 23:40
These are all great Blockchain oriented conferences ([This list](https://docs.google.com/spreadsheets/d/1_Yx5vorqwGhZrz199cq9oNOLhgGNnAkjgbmxIXRxMsM/edit#gid=0))

to keep this rolling I created [this issue](https://github.com/rchain/bounties/issues/639) for more events that aren't blockchain-centric

**Comment by lapin7** [comment] 2018-04-30 08:46
Please add this to [List of blockchain events for RChain](https://docs.google.com/spreadsheets/d/1_Yx5vorqwGhZrz199cq9oNOLhgGNnAkjgbmxIXRxMsM/edit#gid=0)

Dear Sir,

We are organising the 1st International Cryptocurrency and Blockchain Event in the perfect location at the heart of Europe (Palexpo Geneva in Switzerland).

PALEXPO SA is now associate and stakeholder in Token Connexion.

You will find below a temporary access to our website (still under construction) :
http://token-connexion.com/wp-admin
user : preview              pass : T@kenP@leXpo1

And in attachments the application form, exhibition regulations and exhibition contract.

Please contact us very soon if you want to join us and become a event partner.

Best regards

Olivier PINCHARD
00 (33) 450 645 000
00 (33) 607 78 78 98





TOKEN CONNEXION / PALEXPO
Route François-Peyrot 30, 1218 Le Grand-Saconnex, SWITZERLAND
TEL : +41 22 761 11 11

**Comment by Viraculous** [comment] 2018-04-30 15:56
OK @lapin7 , I will do just that.

**Comment by Viraculous** [comment] 2018-04-30 16:13
@lapin7,
 I couldn't log in the website with the details you gave, do you mind verifying it?

**Comment by Tonyprisca13** [comment] 2018-04-30 16:46
@lapin7  can you verify the log in? it doesn't login from end too

**Comment by kaka56** [comment] 2018-05-02 12:54
@Valentine-Mario how do you appear on the budget sheet to start voting 20% for you and preshcode when you knew you contributed nothing to it rather than messing up previous work that has been done. please do clarify yourself cause i dont see why you should do that leaving my name with a negative reward.

**Comment by Valentine-Mario** [comment] 2018-05-03 04:08
@kaka56 perhaps u should go through it again rather than making unnecessary conclusions. I and @preshcode contributed immensely to the spreed sheet list

**Comment by Valentine-Mario** [comment] 2018-05-03 04:10
I feel u are being bias @kaka56

**Comment by Ojimadu** [comment] 2018-05-27 20:15
@Viraculous See my comment on issues #639.

**Comment by Ojimadu** [comment] 2018-07-02 22:42
Closing this in favour of #743

**Closed by Ojimadu** 2018-07-02 22:42 UTC
Labels: Events
