### ISSUE TITLE
Concerns surrounding translation work

### ISSUE THREAD

**Issue by Jake-Gillberg** [rchain/bounties#483] opened 2018-03-13 00:04 UTC
Let me start by saying that I am very happy about the excitement surrounding translation. It's great for a few reasons:
1. it supports the message that "RChain is GLOBAL"
2. it's an easy way to have a diverse set of people get involved

Concerns:
 1. Things that don't make sense to translate are being translated (for example, the rosette documentation that is pretty internal to the workings of RChain, and may not even be a part of the stack long term)
 2. There is no strategy surrounding which documents are translated. The way we are going about translations doesn't breed the thought of "what things are important to have translated?" or "If a user is looking for RChain documents in language X, what will they find?"
 3. It is hard to evaluate the work done on translations
 4. Translation issues bringing illegitimacy to the bounty program and driving people away from it
 5. Translation work being dominated by a small number of individuals per language, reducing the benefits of drawing more people into this relatively easy entry point to the bounty program. 

Personally, I don't feel like I have the time to dig through and understand which translation issues are important, worthwhile, or work well done, so I feel uncomfortable participating in the budgeting process that would make my discomforts heard on these issues.

Solutions that I think could help:
 - If I could delegate my vote to someone who I trusted to keep the concerns proposed above in mind, I totally would.
 - Have a report on the budget that is being spent out of the bounty program, where breakdowns are rationalized and justified
 - Put some sort of limit or cap on translation issues
 - Have someone claim responsibility for translation issues and have their own mini funded "translation bounty" program

Here are a few numbers:
 - As of writing this issue there are 50 open translation issues, 28% of all open issues
 - @lapin7, @dckc could you help me find how much money went to translation issues last month, as a number and percentage of total rewards? And how much is projected for this month?

**Comment by dckc** [comment] 2018-03-13 00:51
Thanks for sharing your concerns. In some sense, this looks like the resolution to #302 is inadequate and hence it should be reopened.

> Have someone claim responsibility for translation issues ...

@ICA3DaR5 has taken on a "guiding" role (cf. #477 401) ...

> and have their own mini funded "translation bounty" program

but it doesn't go that far.

**Comment by deannaduke** [comment] 2018-03-13 01:09
#4. YES. This issue needs to be corralled sooner rather than later if you want to preserve any sense of legitimacy.

**Comment by Jake-Gillberg** [comment] 2018-03-13 01:45
@deannaduke Thanks for the support, I added that one (and was driven to finally write this issue) after I heard some of those sentiments expressed by a few people. Could you clarify what, exactly, you see as the cause of degradation of legitimacy? The amount of money spent on these issues? The quality or organization of the output? Also, do any of the solutions proposed above resonate with you? Do you have other ideas?

**Comment by deannaduke** [comment] 2018-03-13 03:24
Well, as a developer looking to contribute to the project, when you go into GitHub bounties, it's a long list of seemingly unvetted requests for services with large price tags. This is a turn-off because it has the feel that no one is minding the store and there's some huge scam going on. I think a lot of people don't want to contribute because they don't want to be associated with potential scam work. And nobody likes the possible mismanagement of funds. It just feels dirty and the whole cryptocurrency space doesn't need any more negatives thrown on it.

It would go a long way if there was a better method of managing what requests are approved (before they even show up), based on actual need and value of the work suggested. As much as I love translations into other languages and some of the other issues submitted, what's the value/future benefit of that work for each language and topic translated? Is it worth the amount being spent on it?

As far as I can tell, not a whole lot of analysis is being done on the issues submitted. It gives people the impression that we're getting fleeced and are totally unsophisticated at requesting bounty work. I would suggest having one or more point people responsible for vetting _all_ requests coming in, approving them to be worked on, and valuing them. The whole "find 2 friends" to approve completed work is too easy to corrupt, so having a body of people to approve the finished work would reduce that problem as well. Identifying the top 3 - 5 languages we want translation services done for and the kind of content we want translated (in other words, guidelines for translation) would also help eliminate a lot of the submissions.

I'm just spitballing at this point, but more organization and guidance is definitely needed.

**Comment by lapin7** [comment] 2018-03-13 07:50
@deannaduke and @Jake-Gillberg thanks for your observations.

March will be better. The spreadsheet solution served well as a prototype, but it has clearly come to a drastic end. The new system will be much better, see https://rewards.rchain.coop/ .
The goal is not to have bodies of people that approve issues. I want to give to everybody the possibility of giving a carrot or using a stick. So there have to be at least 3 persons to support an issue and to claim a budget. But all the others can increase or decrease the budgets cq. rewards. This power must be effective, because people just at numbers and percentages, instead of discussions as raising concerns. If needed,  then people can explain why they increased or decreased a budget for an issue. So @Jake-Gillberg could give a 0 budget to issues that he's not comfortable with or even give a negative budget. He also could invite other people to vote down certain issues.
Until now we're in a learning process and we allow for some bounties that are not allocated appropriately.
Also the description of issues is more going towards SMART descriptions and not merely brain dumps. People have to recognize that when they formulate an issue in a poor way, that it means for readers a lot of work to understand what the issue is about.

**Comment by ResonanceXX** [comment] 2018-03-13 08:10
The web application site looks very dependable.
And this is a welcome solution to the various issues we have had using spread sheets.

Another step forward in the right direction. Cheers!

**Comment by dckc** [comment] 2018-03-13 08:20
@deannaduke 
> It would go a long way if there was a better method of managing what requests are approved (before they even show up), 

catch-22, no? How does anybody manage requests before they show up anywhere?

**Comment by Barkov-F** [comment] 2018-03-13 12:03
I agree that translation and localization work is now in disorder. Maybe we should make road-maps for our marketing and localization efforts in relevant languages? 

First, I think the community has to decide on the list of the **canonical texts, videos and docs** that are vital for understanding what RChain project is all about. The documents on than list (I think it has to be short, 10 items or less) will have a priority in translation into new languages. Think of it like starter-packs for the potential developers and other contributors, who are not native English speakers. Then we can assign the fixed bounties for that pack translation and subsequent review by a native speaker.
    
Also, I think that the coop should **localize developers.coop** site and keep local languages versions up-to-date. Based on the site analytics [#454](https://github.com/rchain/bounties/issues/454), Chinese, Russian, and English settings visitors add up to almost 80% of total guests, the next 10 locales stand for less than 10%, so I think we should do that three languages first and latter add other languages over certain threshold (like 1% of visitors) if the coop has both human and financial resources to do that.

Translation work, in my view, has to be more **aligned with marketing activities**, like preparing the multi-language releases about milestones in platform development or multi-language subtitled promotional interviews. Maybe there will be a need to tweak marketing messages for different audiences.

**Comment by Ojimadu** [comment] 2018-03-13 13:10
I actually don't like the idea of translating any document one can find. Some of these translations might translate documents that are out of date or redundant. While the multiple translation work going on is good in a way, there is a need to define:
- What languages are needed for the translation (I suggest we start with the top 3 spoken languages save for English)
- What documents needs to be translated. I would prefer seeing tutorial documents like [Contributing.MD](https://github.com/rchain/Members/blob/master/CONTRIBUTING.md), FAQs, whitepaper and maybe, some getting started tutorials and interviews as approved by an authority (Board member? Marketing Work group? etc.) being translated rather than any document. 

However if a translator  is convinced and can proof that there is an active audience (communities, groups, meet ups etc.) for any language or document, then they should give it a try.

**Comment by dckc** [comment] 2018-03-13 14:28
Conventionally it's best not to evaluate suggestions until a round of brainstorming is mostly done, but I have developed a muscle that twitches when I hear / see "we should" rather than "I volunteer to ..." or "Fred, would you please ..." and I'm not sure I'll remember later, so...

### Transparency and Issue list maintenance by guides

> I would suggest having one or more point people responsible for vetting _all_ requests coming in, approving them to be worked on, and valuing them.

Some of us are doing that in #401. You're more than welcome to participate or help find others to share the load.

> It is hard to evaluate the work done on translations

I very much share this concern (see my Feb 12 comment in #302 ).

The best approach I have found is issue guides; @ICA3DaR5 has stepped up, but he has only so much bandwidth. Is anyone in a position to help him?

> ... So @Jake-Gillberg could give a 0 budget to issues that he's not comfortable with ...

I don't think putting the burden on people in his position (which is also my position) can work. By and large, people follow the path of least resistance. It's easier to just not bother than to get into a confrontation. And Jake's (and my) expertise is not in translation, so there's no inherent legitimacy to any criticism he (or I) might give.

### Delegation

>  If I could delegate my vote to someone who I trusted to keep the concerns proposed above in mind, I totally would.

Yes, the loose access control in the spreadsheet system allowed that; so to a certain extent, the web app is a regression in this area. I opened #484 to look into that.

### The coalition-of-three risk

> The whole "find 2 friends" to approve completed work is too easy to corrupt, so having a body of people to approve the finished work would reduce that problem as well. 

The best two approaches I have thought of are
  - a trust metric to give some votes more weights when averaging #375
  - slashing conditions so that any bad behavior puts all of a person's reward at risk #261

### Which documents to translate?

> First, I think the community has to decide on the list of the canonical texts, videos and docs ...

Any suggestions on how we would do that?

Our approach so far (in ISSUE_TEMPLATE.md) is to
  1. defer to those who chose the https://github.com/rchain/reference documents and
  2. ask that translators justify any work on other documents.

I suppose any one of us could make a pull request to edit ISSUE_TEMPLATE.md to replace the pointer to `/reference` with a specific list of documents. But curating them separately seems unwise, to me...

> ... for example, the rosette documentation that is pretty internal to the workings of RChain ...

I found it pretty useful; but I might have found it even if it were in a more obscure place... If it's not important documentation for the community, then it shouldn't be in https://github.com/rchain/reference , should it? Perhaps raise an issue or make a pull request there?

### Bounty effort is not fungible

> I think we should do that three languages first and latter add other languages over certain threshold (like 1% of visitors) if the coop has both human and financial resources to do that.

If someone shows up with skill and interest in Italian translation, it does little good to say "you really should do Chinese; the audience is much bigger."

This is not a zero-sum game; effort spent on Italian translation doesn't take away from effort spent on Chinese translation. It can make the work on Chinese translation a little harder to coordinate; that's why I invested in a label for China-related issues.

What we _can_ do is say "we'll reward Chinese translation more because the audience is bigger." Each of us has the right, duty, and obligation to do so. But delegating to guides sure would be nice. Again... any volunteers, please?

### developer.rchain.coop is contracted to Pyrofex

> I think that the coop should localize https://developer.rchain.coop/ site and keep local languages versions up-to-date.

The coop contracted maintenance of that site to pyrofex. Please contact @MParlikar (cf. #184). Oh... I suppose there's a counter-party  within the coop who did the contracting. I don't know who that is, though. @kennyrowe would know, I suppose.

**Comment by ICA3DaR5** [comment] 2018-03-13 18:31
My instructions so far have been to leave the translators free on translating the reference contents. Including the Rosette PDF.

**Comment by Keaycee** [comment] 2018-03-14 13:35
@Jake-Gillberg and @deannaduke Thank you for your observation.

I agree with @deannaduke that there are a lot of scam going on without minding the store. I think there should be a bounty limit a coop member can attain. This is because some member take advantage of the decentralized system by creating issues that has no prospect or probably just to gain more budget. Some members be like **"Creating 10 to 16 or more issues in a month"** Why? Because they want to indirectly take advantage of the system without being caught and also having more budget to them self. For example, A coop member having above $15,000 as a reward in a month is very awful. There is a need to to have a bounty limit per individual, as it may help to cub down the fraud intent of members.

**Comment by Jake-Gillberg** [comment] 2018-03-14 14:49
@Keaycee The number of issues opened by a contributor or the amount they receive in a month shouldn't be a problem if all work was being reimbursed fairly. More money spent in a month should equal more value created. Your argument for caps relies on the assumption that the bounty program isn't spending money to create value.

**Comment by Jake-Gillberg** [comment] 2018-03-14 14:52
> What we can do is say "we'll reward Chinese translation more because the audience is bigger."

@ICA3DaR5 What are the standard rules-of-thumb for reimbursement for translation issues? Is it a uniform  $/word for all documents? Or do we have a budgeting preference towards a subset of languages? Also, are video subtitles and written documents reimbursed similarly? I would imagine that a translated written document is worth more than translated subtitles.

**Comment by Jake-Gillberg** [comment] 2018-03-14 14:54
Also @ICA3DaR5, can you answer the question posed above as to how much money (raw, and as a percentage of total dollars coming out of the bounty program) was spent on translation last month, and how much may be on the deck for this month?

**Comment by dckc** [comment] 2018-03-14 15:15
@Jake-Gillberg I can give you a design for computing those dollar amounts:
  - use the github graphql API to select the issues with label translation
  - grab the monster spreadsheet and use pandas to normalize it (see [dbr_norm1.py](https://github.com/dckc/rchain-dbr/blob/master/dbr_norm1.py)
  - compute the desired result straightfowardly with pandas

I think it would take me between 0.5 and 2 hours. But I'm inclined to spend the time on the trust metric...

**Comment by Jake-Gillberg** [comment] 2018-03-14 15:37
@dckc, Awesome, thanks. Yeah, please spend that time on the trust metric :)

**Comment by Jake-Gillberg** [comment] 2018-03-14 19:03
Got a number of $30,628.66 for Feb. 2018 across 24 translation issues.

**Comment by dckc** [comment] 2018-03-14 19:12
> Is it a uniform $/word for all documents?

I recall something about an international guideline along these lines that has been used around here... @kitblake maybe you have details?

**Comment by dckc** [comment] 2018-03-14 21:22
@ICA3DaR5 in today's RAM meeting (#469) @9rb expressed a willingness to help guide translation issues; I took the ball to follow up with him. Also, the idea of a specific statement of work to fund management of translations got considerable support.

@9rb are you familiar with putting together SOWs? Perhaps you could share what you know on that topic with @ICA3DaR5 ?

**Comment by dckc** [comment] 2018-03-14 21:25
Actually, now that concerns have been acknowledged, I'd rather close this as a dup of #302 and resume work there. I'll stand by for a little bit before doing so.

**Comment by ICA3DaR5** [comment] 2018-03-14 23:32
@dckc @9rb I have no experience with SOW's, is [this](https://docs.google.com/document/d/127dQJL697v_H2igUc-yqKGFXwaAXMWKOGrkCgaD01lo/edit) a good example of one?

**Comment by dckc** [comment] 2018-03-15 01:45
That's probably much more elaborate than is needed here, but that's the idea, yes.

**Comment by Jake-Gillberg** [comment] 2018-03-15 12:36
@dckc, personally, I would call the issues brought up here broader than concerns surrounding the quality of the work or the template for translation, but I see that the two are related.

Had an idea this morning concerning video translations @ICA3DaR5, @patrick727, I would like to hear your thoughts. As opposed to videos, written documents tend to have clearer and more concise information that is easier to consume. If there are important things said in a video, my preferred pipeline instead of straight subtitle translation would be:

1. Blog post summarizing the information (in any language)
1.? and English at the same time
2. Translation of that blog post

This would kill a couple of birds with one stone: generating content while getting translation work done. Also, if an English version was created by the translator, this would make a great portion of their work easier to verify an English speaking crew.

**Comment by ICA3DaR5** [comment] 2018-03-15 18:28
@Jake-Gillberg IMO it's the same amount of work since one has to watch the video (maybe several times). Why not have the transcript on YouTube (a huge platform) instead of just a blog post?

**Comment by Jake-Gillberg** [comment] 2018-03-15 20:16
@ICA3DaR5 There has been quite a bit of discontent with the large amount of video and lack of written content for this project ([see the most recent message in #pr-opportunities](https://twitter.com/TheJohnPlatts/status/974087978321698818)). If we can generate more-easily digestible written content while doing translation work, we are solving two problems at once.

I disagree that a YouTube video has a wider audience than a blog post. It takes much more commitment to watch a video (hence the complaints).

**Comment by dckc** [comment] 2018-03-17 14:44
While respecting work that was started before this advice became clear, @Jake-Gillberg, @ian-bloom , @ICA3DaR5 , and I have revised the ISSUE_TEMPLATE to reduce the list of documents to translate.

We introduced a [do-not-translate](https://github.com/rchain/bounties/labels/do-not-translate) label that we plan to use to give this advice efficiently.

**Comment by dckc** [comment] 2018-03-21 21:35
The highest budgets and rewards are currently for translations to Russian. That's an important audience according to #454, but in at least one case (#498), the work in progress is not even readily available. So I left a comment requesting a pointer to work-in-progress and, pending a response, down-voted the budget.

#482 is a translation of the whitepaper. Is that important? I'm not inclined to follow up on it just now, but I encourage others to do so.

 - [highest rewards](https://rewards.rchain.coop/index.php?-table=reward&-action=list&-cursor=0&-skip=0&-limit=30&-mode=list&-sort=reward_usd+desc)
 - [highest budgets](https://rewards.rchain.coop/index.php?-table=issue_budget&-action=list&-cursor=0&-skip=0&-limit=30&-mode=list&-sort=budget_usd+desc)

**Comment by ICA3DaR5** [comment] 2018-03-23 14:18
For the blog posts: I think we should move away from Medium and find a platform that supports translations. I don't know of one, but I will research for it.

**Comment by ian-bloom** [comment] 2018-03-24 13:40
@ICA3DaR5 Sometime around last Saturday #403 meeting you expressed your preference for WP [Polylang](https://wordpress.org/plugins/polylang/) over [WPML](https://wpml.org/), and showed me the open source translation platform [Weblate](https://weblate.org/en/).

Since we are looking at tools that play nice with WordPress, how about [GlotPress](https://wordpress.org/plugins/glotpress/)? That is the tool being used by the large volunteer project to [translate WordPress](https://translate.wordpress.org/).

I also like the way their volunteer translation project is structured. Here is their [HANDBOOK](https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/).

WordPress polyglots community even has a [process](https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/#become-a-translation-editor) for screening translators:

> Before your translations become part of WordPress, they will need to be approved by a translation editor – a trusted member of the polyglots community who can also appoint new translation editors.

**Comment by dckc** [comment] 2018-03-24 13:54
@ian-bloom note I made #539 just for the discussion of such tools.

**Comment by ian-bloom** [comment] 2018-03-25 09:00
I do not think that videos or video transcripts are good targets for translation. To make content more accessible, videos should be first summarized into blog posts, and then **only the summaries should be translated.** This makes the content far easier to access by readers and can be consumed in less time. Blog summaries of videos can contain screenshots and links to particular times in the video so that the readers know exactly where to go when they need more detail than provided by the summary.

**Comment by Jake-Gillberg** [comment] 2018-04-02 02:40
@AyAyRon-P did some work gathering stats that will be useful in prioritizing language targets. He also did some research into costs associated with outsourcing translation work to third parities. Hopefully both of these will result in more sensible budget recommendations.

@AyAyRon-P, take it away.

**Comment by AyAyRon-P** [comment] 2018-04-03 01:36
Thanks @Jake-Gillberg 

Here were my initial findings - https://docs.google.com/document/d/1LXSsZgoe78Afo3LhJeTwURDiSFK2ldg2p-1_VJiw5wI/edit?usp=sharing

and quotes I received for translations of the RCHAIN ARCHITECHTURE DOCUMENT with a 7 Day turnaround time:  
https://cdn.discordapp.com/attachments/406191011564617748/418090089776807946/Screen_Shot_2018-02-27_at_10.58.00_AM.png

https://cdn.discordapp.com/attachments/406191011564617748/418090104305745941/Screen_Shot_2018-02-27_at_10.58.42_AM.png


**Part 1:** 
Create a poll on the issue - What top 5 languages should we translate into:
List out 20 top most spoken languages and have a spot for other. 

**Part 2:** Generate a list of documents that need translated and a pre-set bounty on them

**MOST SPOKEN LANGUAGES:**
https://www.babbel.com/en/magazine/the-10-most-spoken-languages-in-the-world
https://www.statista.com/chart/12868/the-worlds-most-spoken-languages/
http://mentalfloss.com/article/67766/worlds-top-20-languages-and-words-english-has-borrowed-them

**Chinese - 1.284b
Spanish - 437m
English - 372m
Arabic - 295m
Hindi - 260m
Bengali - 242m
Portuguese - 219m
Russian - 154m 
Japanese - 128m
Lahnda - 119m**
_Above is from Statista in 2017_
-------------------------------------------------------
_Below is from Mentalfloss in 2015_
Javanese - 84m
German - 78m
Korean - 77m
French - 75m
Telugu - 74m
Marathi - 71m
Turkish - 70m
Tamil - 69m
Vietnamese - 68m
Urdu - 64m

**BEST COUNTRIES FOR SOFTWARE DEVELOPERS/ENGINEERS**
http://www.hackerearth.com/blog/competitive-programming/best-countries-software-engineers-developers-work-2017/
https://blog.hackerrank.com/which-country-would-win-in-the-programming-olympics/

**BLOCKCHAIN INNOVATION**
https://venturebeat.com/2017/04/16/global-blockchain-innovation-u-s-lags-europe-and-china-lead/

**MOST ICOs BY COUNTRY**
https://hackernoon.com/10-world-countries-with-the-most-vibrant-ico-scene-44273900701a

Estonia
Cyprus
Slovenia
Switzerland
Russia
UAE
Singapore
UK
Turkey

**MOST CRYPTO FRIENDLY COUNTRY**
https://cryptoslate.com/top-10-most-crypto-friendly-countries/
https://news.bitcoin.com/worlds-top-10-bitcoin-friendly-countries/


**CRYPTOCURRENCY BY COUNTRY**
https://blogs.thomsonreuters.com/answerson/world-cryptocurrencies-country/

**Comment by kitblake** [comment] 2018-04-17 06:17
Results so far for the translation languages poll:
![langranking](https://user-images.githubusercontent.com/912545/38851797-923bd2b2-4217-11e8-91c6-26a254f77059.png)
Please add your $0.02 (takes 2 minutes :)
Anyone with the link can participate: https://www.loomio.org/p/yJBqS539/what-languages-should-the-co-op-communicate-in-

**Comment by AyAyRon-P** [comment] 2018-04-29 13:43
@Jake-Gillberg @kitblake I was looking for final consensus here, are we only translating the top 5? top 10? languages?

**Comment by Jake-Gillberg** [comment] 2018-04-29 14:08
@AyAyRon-P I'm not an authority in those matters. And honestly, I don't even have an opinion there.

**Comment by dckc** [comment] 2018-05-19 13:15
@truffard writes in #711:
> @lapin7 said specifically that one must be a native speaker in order to take part in a translation issue.

Did he? In what context? Always cite your sources. Because I'm not aware that @lapin7 has any executive authority over what participants may or may not choose for their tasks. He may value some things less than others, but each of us has that authority, to the extent granted by our peers by the trust metric (#375).

> @dckc why is it that we have to remind the same rules over and over again?

Well, because not everyone is born knowing these things, right? Discussing our values repeatedly is what establishes them as our values. We can get the computer to remind people of things we think are important by putting them in [ISSUE_TEMPLATE][tpl]. Note @ICA3DaR5's exhortation to "Please fill the **For Translators** section." That's the role of a guide. Implicitly, he's saying "The community is not likely to support a budget for this task until you fill it out in such a way that it makes clear the value of the task to RChain."

The guidance there is not that one must be a native speaker, but that "at least two of them have high proficiency" along with some evidence / reputation to back their claims.

If you look at the [annotated view of ISSUE_TEMPLATE][btpl], you'll see that guidance dates back to Feb 21, based on my Feb 21 checklist suggestion in #302. (I also approved the the relevant PR, #398). (@ICA3DaR5 in the future, if you put more of this "paper trail" in the commit message, everyone can see it from the blame view.) This checklist enjoys a sort of "wiki-consensus"; that is: since any one of us could have changed it, and none of us did, we call consent to it.

Anyone who thinks being a native speaker should be a requirement should submit a pull request to change ISSUE_TEMPLATE.

[tpl]: https://github.com/rchain/bounties/blob/master/ISSUE_TEMPLATE.md
[btpl]: https://github.com/rchain/bounties/blame/master/ISSUE_TEMPLATE.md

**Comment by dckc** [comment] 2018-06-30 05:37
@allancto would you please propose an edit to `ISSUE_TEMPLATE.md` regarding your [suggestion][1] of _value added translation_?

[1]: https://github.com/rchain/bounties/issues/672#issuecomment-395109228

cc @deannald

**Comment by dckc** [comment] 2018-06-30 22:11
@ICA3DaR5 @michaelizer @zero-andreou would you please conctact @PatrickM727 , @kitblake , and / or @pmoorman about getting them to certify you in the trust metric to reflect that Marketing delegates Translation guiding?

**Comment by ICA3DaR5** [comment] 2018-07-01 15:18
@dckc I am on it!

**Comment by dckc** [comment] 2018-07-23 20:31
@AyAyRon-P thanks for stepping up to guide Translation. Note that @allancto did respond to my Jun 30 request with PR #826. I closed that pull request not because the gist of that pull request is no good but because it doesn't follow version control best practices. Please follow up with @allancto on the boundary between **Translation** and **Community Building**.

**Comment by dckc** [comment] 2018-07-26 21:19
See also discussion of valuation in #841

**Comment by dckc** [comment] 2018-08-31 18:30
@allancto 's efforts are elsewhere.

For an example of current thinking in translation, see https://github.com/rchain/bounties/issues/936#issuecomment-417670095 .

**Closed by dckc** 2018-08-31 18:30 UTC
Labels: Operations, Translation

**Comment by dckc** [comment] 2018-09-20 14:56
Concerns around the bounty system (especially Translation) re-surfaced, after RCon3, resulting in a reboot of the bounty system. For details, see: https://github.com/rchain/bounties/issues/783#issuecomment-423171144
